In [52]:
import pandas as pd

EKSPLORASI DATA

In [53]:
df_raw = pd.read_csv(r"D:\LATHIFAH HUSNUN\Work\urbansolv-test\data\raw_data.csv")


print("Data raw:", df_raw.shape)

print("Kolom data raw:")
print(df_raw.columns.tolist())

Data raw: (154, 13)
Kolom data raw:
['nama_tempat', 'alamat', 'jenis_bisnis', 'rating', 'jumlah_bintang', 'jumlah_review', 'jam_operasional', 'harga', 'latitude', 'longitude', 'telepon', 'website', 'kategori']

In [54]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nama_tempat      154 non-null    object
 1   alamat           154 non-null    object
 2   jenis_bisnis     144 non-null    object
 3   rating           154 non-null    float64
 4   jumlah_bintang   154 non-null    int64
 5   jumlah_review    149 non-null    float64
 6   jam_operasional  126 non-null    object
 7   harga            100 non-null    object
 8   latitude         154 non-null    float64
 9   longitude        154 non-null    float64
 10  telepon          114 non-null    object
 11  website          0 non-null      float64
 12  kategori         154 non-null    object
dtypes: float64(5), int64(1), object(7)
memory usage: 15.8+ KB

In [55]:
df_raw = df_raw.drop(columns=["kategori"])

In [56]:
print(df_raw.columns.tolist())

['nama_tempat', 'alamat', 'jenis_bisnis', 'rating', 'jumlah_bintang', 'jumlah_review', 'jam_operasional', 'harga', 'latitude', 'longitude', 'telepon', 'website']

In [57]:
# Tambahkan nomor urut 1–156
df_raw["no"] = range(1, len(df_raw) + 1)

# Tampilkan semua data
print(
    df_raw[["no", "nama_tempat", "alamat", "jenis_bisnis"]]
    .to_string(index=False)
)

 no                                                                            nama_tempat                                                                                                                                    alamat                jenis_bisnis
  1                                                              Bakmi Serangkai Tembalang                                                  Jl. Mulawarman Raya No.11, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50264                Restoran Mie
  2                                                                 BAKSU (Bakmie & Katsu)                                                      Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277                Restoran Mie
  3                                                               Bakmi Surabaya Cak Dul 2                                               Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278                Restoran Mie
  4                                                             Mie Ayam Jakarta Bang Mail                                                 Jl baskoro no, 75, RT.3/RW.7, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275                Restoran Mie
  5                                                                            Bakmi Juned                                                              Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
  6                                                                 Bakmie Jowo "Mas Anto"                                                     Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
  7                                                        Mie Surabaya Cak Bagus Ketileng Depan SDIT Tunas Harapan, Ruko Mutiara Gading A4, Jl. Ketileng Indah Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
  8                                                               Bakmi Surabaya Cak Baron                                               XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
  9                                                         Bakmi Dan Nasi Goreng Cak Budi                                                        Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276        Restoran Nasi Goreng
 10                                                            WARPAD Yamien & Ayam goreng                                                       Jl. Gondang Barat I No.7, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277 Kedai Sarapan & Makan Siang
 11                                                                        Bakmie Suroboyo                                                     XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 12                                                                 Bakmi Surabaya cak zun                                                 Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 13                                                                    Bakmi Jowo Mas Agus                                                 XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 14                                                                         Bakmie Pak Wi'                                                XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 15                                                               Bakmie Surabaya Mas Nopi                                              Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274                Restoran Mie
 16                                                                    Bakmi Jowo Mas Agus                                                      Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
 17                                                           Mie Ayam Lada Hitam Si Jonti                                                          Jl. Bukit Elang A, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 18                                                                   BAKMI JOWO KANG DOEL                                                                   XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274                Restoran Mie
 19                                                             BAKMI JOWO GM GAJAH MAKMUR                                              Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248                    Restoran
 20                                                                         Mie Ayam Happy                                                    Jl. Kedungmundu No.510A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 21                                                                    Bakmi Jowo Mas Agus                                                 XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 22                                                                    Bakmi Jowo Mas Agus                                                      Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
 23                                                          PONDOK Bakmi Surabaya Cak DUL                                                 WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277        Warung Makanan Kecil
 24                                                                     Mie Aceh Bang Wali                                                         Jl. Banjarsari No.38, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275                Restoran Mie
 25                                                            WARPAD Yamien & Ayam goreng                                                       Jl. Gondang Barat I No.7, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277 Kedai Sarapan & Makan Siang
 26                                                               Bakmi Surabaya "cak Pri"                                   Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 27                                                             Pondok Nasi Goreng dan Mie                                                       Jl. Gondang Tim. V No.37, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50175        Restoran Nasi Goreng
 28                                                                         Bakmi Kongsian                      Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                 Rumah Makan
 29                                                                    Mie Goceng Semarang                                                                       WCPP+VC5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277                Restoran Mie
 30                                                                Bakmie Jowo Mas Jenggot                                                    Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 31                                                             BAKMI JOWO GM GAJAH MAKMUR                                              Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248                    Restoran
 32                                                         Raja Murah (Penyet & Mie Jawa)                                                        Jl. Kedungwinong I No.3, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 33                                                                  Bakmi Jowo Pak Brewok                                          Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 34                                                        Mie Ayam dan Bakso Mas Gondrong                                                   Jalan Timoho Raya 1Tembalang, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277              Restoran Bakso
 35                                                                         Bakmi Surabaya                               Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 36                                                                   BAKMI JOWO KANG DOEL                                                                   XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274                Restoran Mie
 37                                                 BAKMI SUROBOYO MAS NDUT (YUDI),METESEH                                                          Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 38                                                        BAKMIE SURABAYA CAK BAGUS GROUP                                                WFVC+7CQ, Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 39                                                       WR Rizqi 99/ Mie Ayam Jakarta 99                                                    Jl. Mulawarman Sel. II No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278                    Restoran
 40                                                                         Mie Ayam Happy                                                    Jl. Kedungmundu No.510A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 41                                                           Mie Ayam Lada Hitam Si Jonti                                                          Jl. Bukit Elang A, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 42                                                         Mie Fil Fil & Cuanki Tembalang                                                         Jl. Timoho Raya No.292, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 20272                Restoran Mie
 43                                                  (MUBAL) Mie Ayam Bumbu Bali Tembalang                                                Jl. Banjarsari Selatan No.18a, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275                    Disimpan
 44                                                                  Pondok Bakmi Bu Tarno                                                XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Tembalang, Semarang City, Central Java 50273                        Kafe
 45                                                                    Bakmi Jowo Mas Ndut                                                 Jl. Dinar Elok Raya No.K2 No.5, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 46                                                                    Bakmi Jowo Pak Gito                                                 XFF5+9Q6, Jl. Sambiroto Raya, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
 47                                                                         Mie Ayam Sakti                                                         Jl. Tunjungsari No.2, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275                Restoran Mie
 48                                                       Mie Bandung Gg. Belakang Pak Min                                                      Kedungmu, Jl. Kedungmundu, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 49                                                                      Bakmi jowo Petruk                                                       Jl. Fatmawati No.175, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 50                                                Bakmi jowo dan nasi goreng bintang lima                                      Depas puskesmas Jl. Kompol R Soekanto, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272        Restoran Nasi Goreng
 51                                                                     Bakmi Jowo Bu Hadi                                        Jalan Prof. Suharso ,Meteseh, Tembalang, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 52                                                                    Mie Ayam Pak Jumali                                                XF37+3FC, Jl. Durenan Indah, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 53                                                             Mie Ayam Pangsit Babaliyut                                                         Jl. Gondang Raya No.28, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277                  Lihat foto
 54                                                   Bakmi Jowo Nasi Goreng KADONG TRESNO                                                    Jl. Sambiroto Raya No.45A, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
 55                                                                       Bakmi Jowo Risqi                                             Jl. Bougenville Dalam No.Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 56                                                                    Bakmi Jowo Mas Nang                                                      perum klipang Blk. P XIV, Sendangmulyo, Tembalang, Semarang City, Central Java 50272                Restoran Mie
 57                                                                  Mie Ayam 99 Fatmawati                                                       Jl. Fatmawati No.163, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 58                                                                    Bakmi jowo pak wito                                                          Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272               Restoran Asia
 59                                                                     Bakmi Jowo Mas Jon                                      XF2H+RJR, Bundaran Simpang 4 Jl. Klipang, Sendangmulyo, Tembalang, Semarang City, Central Java 50272                Restoran Mie
 60                                                                  Bakmi Nyemek Keluarga                                                Perum Jl. Wanamukti No.16 Blok E4, Sambiroto, Tembalang, Semarang City, Central Java 50276                Restoran Mie
 61                                                                     Mie Aceh Jambo aye                                                    Jl. Bukit Elang C No.03, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 62                                                                 Bakmi Jowo Pak Waris 2                                               XFC9+W3W, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 63                                                 Nasi Goreng & Bakmi Jawa (Graha Metro)                                                       Graha Metro No.12B Blk B, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                    Restoran
 64                                                                        Bakmi Jowo Solo                                              Jl. Tulus Harapan No.4 Blk C, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                         NaN
 65                                                       BAKSO & MIE AYAM "PREMIER" UNDIP                                                     Jl. Prof. Soedarto No.16, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275              Restoran Bakso
 66                                                                   Bakmi Jowo Sederhana                                               Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273                Restoran Mie
 67                                                                   Bakmi Jowo Pak Harno                                                                       WFQ7+R2R, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 68                                                            Bakmi surabaya mas gondrong                                        Klipang blok R 7 No.7, RT.05/RW.06, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                         NaN
 69 Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275                                                 WCQQ+M8C, Gg. Nirwana Sari I, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275                    Restoran
 70                                                                   Bakmi Jowo mas Karyo                                                   XF99+X3F, Jl. Wanamukti, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 71                                                              Kedai Mie Aceh Pidie 2018                                                Jl. Dinar Elok Raya No.9 Blok B, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271                Restoran Mie
 72                                                                      Bakmi Jowo Pak No                                                                     XFG6+25P, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276                Restoran Mie
 73                                                 Mie Kopyok dan Mie Ayam Seger Pak Tris                                                 WFV7+38W, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277                Restoran Mie
 74                                                                   Bakmi Jowo Pak triss                                                                   XFQ3+RXP, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273           Restoran Keluarga
 75                                       Mie Ayam & Bakso Barokah pak ndut"Wong Wonogiri"                                                      Jl. Raya Mangun Harjo, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272                Restoran Mie
 76                                               Warung TUMAN - Nasi Goreng & Bakmi Tuman                                                                                 Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271        Restoran Nasi Goreng

CEK DATA DUPLIKAT

cek duplikat berdasarkan nama + alamat

In [58]:
dup_nama_alamat_raw = df_raw[
    df_raw.duplicated(
        subset=["nama_tempat", "alamat"],
        keep=False
    )
]

dup_nama_alamat_no_dup = df_raw[
    df_raw.duplicated(
        subset=["nama_tempat", "alamat"],
        keep=False
    )
]

In [59]:
print("Raw:")
print("Jumlah:", len(dup_nama_alamat_raw))
display(dup_nama_alamat_raw)

Raw:
Jumlah: 30

,nama_tempat,alamat,jenis_bisnis,rating,jumlah_bintang,jumlah_review,jam_operasional,harga,latitude,longitude,telepon,website,no
9,WARPAD Yamien & Ayam goreng,"Jl. Gondang Barat I No.7, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Kedai Sarapan & Makan Siang,4.5,5,496.0,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu Tutup  | Senin 10.00–21.00  | Selasa 10.00–21.00 ,Rp 1–25.000,-7.062719,110.438956,0823-3675-1133,NaN,10
12,Bakmi Jowo Mas Agus,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,29.0,Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu 17.00–00.00  | Senin 17.00–00.00  | Selasa 17.00–00.00 ,NaN,-7.037619,110.468281,0819-0437-2937,NaN,13
15,Bakmi Jowo Mas Agus,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.5,5,99.0,Rabu 17.00–02.00  | Kamis 17.00–02.00  | Jumat 17.00–02.00  | Sabtu 17.00–02.00  | Minggu 17.00–02.00  | Senin 17.00–02.00  | Selasa 17.00–02.00 ,NaN,-7.032360,110.458110,0858-0213-9915,NaN,16
16,Mie Ayam Lada Hitam Si Jonti,"Jl. Bukit Elang A, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.5,5,2059.0,Rabu 09.00–20.00  | Kamis 09.00–20.00  | Jumat 09.00–20.00  | Sabtu 09.00–20.00  | Minggu 09.00–20.00  | Senin 09.00–20.00  | Selasa 09.00–20.00 ,Rp 1–25.000,-7.041073,110.466053,NaN,NaN,17
17,BAKMI JOWO KANG DOEL,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Mie,4.9,5,16.0,Rabu 15.30–23.30  | Kamis 15.30–23.30  | Jumat 15.30–23.30  | Sabtu 15.30–23.30  | Minggu 15.30–23.30  | Senin 15.30–23.30  | Selasa 15.30–23.30 ,NaN,-7.021003,110.456780,0812-2556-0512,NaN,18
18,BAKMI JOWO GM GAJAH MAKMUR,"Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248",Restoran,4.9,5,30.0,Rabu 10.00–02.00  | Kamis 10.00–02.00  | Jumat 10.00–02.00  | Sabtu 10.00–02.00  | Minggu 10.00–02.00  | Senin 10.00–02.00  | Selasa 10.00–02.00 ,Rp 1–25.000,-7.007305,110.448846,0823-2276-4326,NaN,19
19,Mie Ayam Happy,"Jl. Kedungmundu No.510A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.6,5,2580.0,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu 10.00–21.00  | Senin Tutup  | Selasa 10.00–21.00 ,Rp 1–25.000,-7.023494,110.458807,0812-2824-444,NaN,20
20,Bakmi Jowo Mas Agus,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,29.0,Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu 17.00–00.00  | Senin 17.00–00.00  | Selasa 17.00–00.00 ,NaN,-7.037619,110.468281,0819-0437-2937,NaN,21
21,Bakmi Jowo Mas Agus,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.5,5,99.0,Rabu 17.00–02.00  | Kamis 17.00–02.00  | Jumat 17.00–02.00  | Sabtu 17.00–02.00  | Minggu 17.00–02.00  | Senin 17.00–02.00  | Selasa 17.00–02.00 ,NaN,-7.032360,110.458110,0858-0213-9915,NaN,22
24,WARPAD Yamien & Ayam goreng,"Jl. Gondang Barat I No.7, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Kedai Sarapan & Makan Siang,4.5,5,496.0,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu Tutup  | Senin 10.00–21.00  | Selasa 10.00–21.00 ,Rp 1–25.000,-7.062719,110.438956,0823-3675-1133,NaN,25
30,BAKMI JOWO GM GAJAH MAKMUR,"Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248",Restoran,4.9,5,30.0,Rabu 10.00–02.00  | Kamis 10.00–02.00  | Jumat 10.00–02.00  | Sabtu 10.00–02.00  | Minggu 10.00–02.00  | Senin 10.00–02.00  | Selasa 10.00–02.00 ,Rp 1–25.000,-7.007305,110.448846,0823-2276-4326,NaN,31
35,BAKMI JOWO KANG DOEL,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Mie,4.9,5,16.0,Rabu 15.30–23.30  | Kamis 15.30–23.30  | Jumat 15.30–23.30  | Sabtu 15.30–23.30  | Minggu 15.30–23.30  | Senin 15.30–23.30  | Selasa 15.30–23.30 ,NaN,-7.021003,110.456780,0812-2556-0512,NaN,36
39,Mie Ayam Happy,"Jl. Kedungmundu No.510A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.6,5,2580.0,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu 10.00–21.00  | Senin Tutup  | Selasa 10.00–21.00 ,Rp 1–25.000,-7.023494,110.458807,0812-2824-444,NaN,40
40,Mie Ayam Lada Hitam Si Jonti,"Jl. Bukit Elang A, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.5,5,2059.0,Rabu 09.00–20.00  | Kamis 09.00–20.00  | Jumat 09.00–20.00  | Sabtu 09.00–20.00  | Minggu 09.00–20.00  | Senin 09.00–20.00  | Selasa 09.00–20.00 ,Rp 1–25.000,-7.041073,110.466053,NaN,NaN,41
69,Bakmi Jowo mas Karyo,"XF99+X3F, Jl. Wanamukti, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,5.0,Rabu 11.00–21.00  | Kamis 11.00–21.00  | Jumat 11.00–21.00  | Sabtu 11.00–21.00  | Minggu 11.00–21.00  | Senin 11.00–21.00  | Selasa 11.00–21.00 ,Rp 1–25.000,-7.030051,110.467665,NaN,NaN,70
74,"Mie Ayam & Bakso Barokah pak ndut""Wong Wonogiri""","Jl. Raya Mangun Harjo, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.7,5,108.0,Rabu 11.00–21.00  | Kamis Tutup  | Jumat 12.30–21.00  | Sabtu 11.00–21.00  | Minggu 11.30–21.00  | Senin 11.00–21.00  | Selasa 11.00–21.00 ,Rp 1–25.000,-7.044084,110.460798,0819-0978-3837,NaN,75
78,"Bakmi Jowo ""RiLEX"" Nasi Goreng","Jalan Kedung Mundu Raya No.23B, Sambiroto, Tembalang, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Nasi Goreng,4.4,5,21.0,Rabu 19.00–21.00  | Kamis 19.00–21.00  | Jumat 19.00–21.00  | Sabtu 19.00–21.00  | Minggu 19.00–21.00  | Senin 19.00–21.00  | Selasa 19.00–21.00 ,NaN,-7.018516,110.455762,NaN,NaN,79
79,Mie Ayam & Bakso (Mibuli) Pak Rudi,"Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran Mie,4.9,5,32.0,Rabu 11.30–21.00  | Kamis 11.30–21.00  | Jumat 11.30–21.00  | Sabtu 11.30–21.00  | Minggu 11.30–21.00  | Senin 11.30–21.00  | Selasa 11.30–21.00 ,Rp 1–25.000,-7.067521,110.439049,NaN,NaN,80
84,Bakmi Jowo mas Karyo,"XF99+X3F, Jl. Wanamukti, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,5.0,Rabu 11.00–21.00  | Kamis 11.00–21.00  | Jumat 11.00–21.00  | Sabtu 11.00–21.00  | Minggu 11.00–21.00  | Senin 11.00–21.00  | Selasa 11.00–21.00 ,Rp 1–25.000,-7.030051,110.467665,NaN,NaN,85
85,"Bakmi Jowo ""RiLEX"" Nasi Goreng","Jalan Kedung Mundu Raya No.23B, Sambiroto, Tembalang, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Nasi Goreng,4.4,5,21.0,Rabu 19.00–21.00  | Kamis 19.00–21.00  | Jumat 19.00–21.00  | Sabtu 19.00–21.00  | Minggu 19.00–21.00  | Senin 19.00–21.00  | Selasa 19.00–21.00 ,NaN,-7.018516,110.455762,NaN,NaN,86
90,"Mie Ayam & Bakso Barokah pak ndut""Wong Wonogiri""","Jl. Raya Mangun Harjo, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.7,5,108.0,Rabu 11.00–21.00  | Kamis Tutup  | Jumat 12.30–21.00  | Sabtu 11.00–21.00  | Minggu 11.30–21.00  | Senin 11.00–21.00  | Selasa 11.00–21.00 ,Rp 1–25.000,-7.044084,110.460798,0819-0978-3837,NaN,91
93,Mie Ayam & Bakso (Mibuli) Pak Rudi,"Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran Mie,4.9,5,32.0,Rabu 11.30–21.00  | Kamis 11.30–21.00  | Jumat 11.30–21.00  | Sabtu 11.30–21.00  | Minggu 11.30–21.00  | Senin 11.30–21.00  | Selasa 11.30–21.00 ,Rp 1–25.000,-7.067521,110.439049,NaN,NaN,94
133,YOHIKI MIE AYAM,"Jl. Mulawarman, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",Restoran,5.0,5,85.0,Rabu 11.00–23.00  | Kamis 11.00–23.00  | Jumat 11.00–23.00  | Sabtu 11.00–23.00  | Minggu Tutup  | Senin 11.00–23.00  | Selasa 11.00–23.00 ,Rp 1–25.000,-7.067363,110.439052,0821-3224-5915,NaN,134
135,Warung Wasabi,"Jalan Tirto Agung No. 77 Pedalangan Tembalang, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268",Restoran Jepang,4.4,5,2756.0,NaN,Rp 25.000–50.000,-7.060284,110.427574,0818-240-538,NaN,136
136,Yuyake Ramen Ketileng,"Jl. Ketileng Raya No.15, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Jepang,5.0,5,14.0,NaN,Rp 1–25.000,-7.028565,110.468057,0895-1310-0724,NaN,137
137,Ramen Kakek Jepang,"Jl. Tirto Usodo Tim. No.44, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268",Restoran Ramen,3.6,5,32.0,NaN,Rp 1–25.000,-7.058160,110.431136,0813-2845-1701,NaN,138
140,YOHIKI MIE AYAM,"Jl. Mulawarman, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",Restoran,5.0,5,85.0,Rabu 11.00–23.00  | Kamis 11.00–23.00  | Jumat 11.00–23.00  | Sabtu 11.00–23.00  | Minggu Tutup  | Senin 11.00–23.00  | Selasa 11.00–23.00 ,Rp 1–25.000,-7.067363,110.439052,0821-3224-5915,NaN,141
146,Warung Wasabi,"Jalan Tirto Agung No. 77 Pedalangan Tembalang, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268",Restoran Jepang,4.4,5,2756.0,NaN,Rp 25.000–50.000,-7.060284,110.427574,0818-240-538,NaN,147
147,Ramen Kakek Jepang,"Jl. Tirto Usodo Tim. No.44, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268",Restoran Ramen,3.6,5,32.0,NaN,Rp 1–25.000,-7.058160,110.431136,0813-2845-1701,NaN,148
148,Yuyake Ramen Ketileng,"Jl. Ketileng Raya No.15, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Jepang,5.0,5,14.0,NaN,Rp 1–25.000,-7.028565,110.468057,0895-1310-0724,NaN,149

HAPUS DUPLIKAT BERDASARKAN NAMA DAN ALAMAT

In [60]:
df_clean_raw = df_raw.drop_duplicates(
    subset=["nama_tempat", "alamat"],
    keep="first"
)

print("Jumlah data raw   :", len(df_raw))
print("Jumlah data clean :", len(df_clean_raw))
print("Duplikat dihapus  :", len(df_raw) - len(df_clean_raw))

print(
    "Duplikat nama + alamat setelah cleaning:",
    df_clean_raw.duplicated(
        subset=["nama_tempat", "alamat"]
    ).sum()
)

Jumlah data raw   : 154
Jumlah data clean : 139
Duplikat dihapus  : 15
Duplikat nama + alamat setelah cleaning: 0

cleaning karakter aneh di jam operasional

In [61]:
pd.set_option("display.max_colwidth", None)

display(
    df_clean_raw[["nama_tempat", "jam_operasional"]]
    [df_clean_raw["jam_operasional"].notna()]
    .head(20)
)

,nama_tempat,jam_operasional
0,Bakmi Serangkai Tembalang,Rabu 12.00–01.00  | Kamis 12.00–01.00  | Jumat 13.00–01.00  | Sabtu 12.00–01.00  | Minggu 12.00–01.00  | Senin 12.00–01.00  | Selasa 12.00–01.00 
1,BAKSU (Bakmie & Katsu),Rabu 09.00–21.00  | Kamis 09.00–21.00  | Jumat 09.00–21.00  | Sabtu 09.00–21.00  | Minggu 09.00–21.00  | Senin 09.00–21.00  | Selasa 09.00–21.00 
2,Bakmi Surabaya Cak Dul 2,Rabu 07.30–23.30  | Kamis 07.30–23.30  | Jumat 07.30–23.30  | Sabtu 07.30–23.30  | Minggu 07.30–23.30  | Senin 07.30–23.30  | Selasa 07.30–23.30 
3,Mie Ayam Jakarta Bang Mail,Rabu 09.00–18.00  | Kamis 09.00–18.00  | Jumat 09.00–18.00  | Sabtu 09.00–18.00  | Minggu Tutup  | Senin 09.00–18.00  | Selasa 09.00–18.00 
4,Bakmi Juned,Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu Tutup  | Senin Tutup  | Selasa 17.00–00.00 
5,"Bakmie Jowo ""Mas Anto""",Rabu 17.30–00.00  | Kamis Tutup  | Jumat 17.30–00.00  | Sabtu 17.30–00.00  | Minggu 17.30–00.00  | Senin 17.30–00.00  | Selasa 17.30–00.00 
6,Mie Surabaya Cak Bagus Ketileng,Rabu 16.00–23.55  | Kamis 16.00–23.55  | Jumat 16.00–23.55  | Sabtu 16.00–23.55  | Minggu 16.00–23.55  | Senin 16.00–23.55  | Selasa 16.00–23.55 
7,Bakmi Surabaya Cak Baron,Rabu 18.45–23.45  | Kamis 18.45–23.45  | Jumat 18.45–23.45  | Sabtu 18.45–23.45  | Minggu 18.45–23.45  | Senin 18.45–23.45  | Selasa 18.45–23.45 
8,Bakmi Dan Nasi Goreng Cak Budi,Rabu 12.00–00.00  | Kamis 12.00–00.00  | Jumat 12.00–00.00  | Sabtu 12.00–00.00  | Minggu 12.00–00.00  | Senin 12.00–00.00  | Selasa 12.00–00.00 
9,WARPAD Yamien & Ayam goreng,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu Tutup  | Senin 10.00–21.00  | Selasa 10.00–21.00 
10,Bakmie Suroboyo,Rabu 12.00–22.00  | Kamis 12.00–22.00  | Jumat 12.00–22.00  | Sabtu 12.00–22.00  | Minggu 12.00–22.00  | Senin 12.00–22.00  | Selasa 12.00–22.00 
11,Bakmi Surabaya cak zun,Rabu 16.00–23.30  | Kamis 16.00–23.30  | Jumat 16.00–23.30  | Sabtu 16.00–23.30  | Minggu 16.00–23.30  | Senin 16.00–23.30  | Selasa 16.00–23.30 
12,Bakmi Jowo Mas Agus,Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu 17.00–00.00  | Senin 17.00–00.00  | Selasa 17.00–00.00 
13,Bakmie Pak Wi',Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu 17.00–00.00  | Senin 17.00–00.00  | Selasa 17.00–00.00 
14,Bakmie Surabaya Mas Nopi,Rabu 17.00–00.00  | Kamis 17.00–00.00  | Jumat 17.00–00.00  | Sabtu 17.00–00.00  | Minggu 17.00–00.00  | Senin 17.00–00.00  | Selasa 17.00–00.00 
15,Bakmi Jowo Mas Agus,Rabu 17.00–02.00  | Kamis 17.00–02.00  | Jumat 17.00–02.00  | Sabtu 17.00–02.00  | Minggu 17.00–02.00  | Senin 17.00–02.00  | Selasa 17.00–02.00 
16,Mie Ayam Lada Hitam Si Jonti,Rabu 09.00–20.00  | Kamis 09.00–20.00  | Jumat 09.00–20.00  | Sabtu 09.00–20.00  | Minggu 09.00–20.00  | Senin 09.00–20.00  | Selasa 09.00–20.00 
17,BAKMI JOWO KANG DOEL,Rabu 15.30–23.30  | Kamis 15.30–23.30  | Jumat 15.30–23.30  | Sabtu 15.30–23.30  | Minggu 15.30–23.30  | Senin 15.30–23.30  | Selasa 15.30–23.30 
18,BAKMI JOWO GM GAJAH MAKMUR,Rabu 10.00–02.00  | Kamis 10.00–02.00  | Jumat 10.00–02.00  | Sabtu 10.00–02.00  | Minggu 10.00–02.00  | Senin 10.00–02.00  | Selasa 10.00–02.00 
19,Mie Ayam Happy,Rabu 10.00–21.00  | Kamis 10.00–21.00  | Jumat 10.00–21.00  | Sabtu 10.00–21.00  | Minggu 10.00–21.00  | Senin Tutup  | Selasa 10.00–21.00 

In [62]:
# Menampilkan karakter non-ASCII yang muncul pada jam_operasional
chars = set()

for value in df_clean_raw["jam_operasional"].dropna():
    for char in value:
        if ord(char) > 127:
            chars.add((char, ord(char)))

print(chars)

{('–', 8211), ('\ue14d', 57677)}

In [63]:
df_clean_raw["jam_operasional"] = (
    df_clean_raw["jam_operasional"]
    .str.replace("\ue14d", "", regex=False)
    .str.strip()
)

C:\Users\Infinix\AppData\Local\Temp\ipykernel_9016\1118807709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_raw["jam_operasional"] = (

In [64]:
chars = set()

for value in df_clean_raw["jam_operasional"].dropna():
    for char in value:
        if ord(char) > 127:
            chars.add((char, ord(char)))

print(chars)

{('–', 8211)}

In [65]:
pd.set_option("display.max_colwidth", None)

display(
    df_clean_raw[["nama_tempat", "jam_operasional"]]
    [df_clean_raw["jam_operasional"].notna()]
    .head(20)
)

,nama_tempat,jam_operasional
0,Bakmi Serangkai Tembalang,Rabu 12.00–01.00 | Kamis 12.00–01.00 | Jumat 13.00–01.00 | Sabtu 12.00–01.00 | Minggu 12.00–01.00 | Senin 12.00–01.00 | Selasa 12.00–01.00
1,BAKSU (Bakmie & Katsu),Rabu 09.00–21.00 | Kamis 09.00–21.00 | Jumat 09.00–21.00 | Sabtu 09.00–21.00 | Minggu 09.00–21.00 | Senin 09.00–21.00 | Selasa 09.00–21.00
2,Bakmi Surabaya Cak Dul 2,Rabu 07.30–23.30 | Kamis 07.30–23.30 | Jumat 07.30–23.30 | Sabtu 07.30–23.30 | Minggu 07.30–23.30 | Senin 07.30–23.30 | Selasa 07.30–23.30
3,Mie Ayam Jakarta Bang Mail,Rabu 09.00–18.00 | Kamis 09.00–18.00 | Jumat 09.00–18.00 | Sabtu 09.00–18.00 | Minggu Tutup | Senin 09.00–18.00 | Selasa 09.00–18.00
4,Bakmi Juned,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu Tutup | Senin Tutup | Selasa 17.00–00.00
5,"Bakmie Jowo ""Mas Anto""",Rabu 17.30–00.00 | Kamis Tutup | Jumat 17.30–00.00 | Sabtu 17.30–00.00 | Minggu 17.30–00.00 | Senin 17.30–00.00 | Selasa 17.30–00.00
6,Mie Surabaya Cak Bagus Ketileng,Rabu 16.00–23.55 | Kamis 16.00–23.55 | Jumat 16.00–23.55 | Sabtu 16.00–23.55 | Minggu 16.00–23.55 | Senin 16.00–23.55 | Selasa 16.00–23.55
7,Bakmi Surabaya Cak Baron,Rabu 18.45–23.45 | Kamis 18.45–23.45 | Jumat 18.45–23.45 | Sabtu 18.45–23.45 | Minggu 18.45–23.45 | Senin 18.45–23.45 | Selasa 18.45–23.45
8,Bakmi Dan Nasi Goreng Cak Budi,Rabu 12.00–00.00 | Kamis 12.00–00.00 | Jumat 12.00–00.00 | Sabtu 12.00–00.00 | Minggu 12.00–00.00 | Senin 12.00–00.00 | Selasa 12.00–00.00
9,WARPAD Yamien & Ayam goreng,Rabu 10.00–21.00 | Kamis 10.00–21.00 | Jumat 10.00–21.00 | Sabtu 10.00–21.00 | Minggu Tutup | Senin 10.00–21.00 | Selasa 10.00–21.00
10,Bakmie Suroboyo,Rabu 12.00–22.00 | Kamis 12.00–22.00 | Jumat 12.00–22.00 | Sabtu 12.00–22.00 | Minggu 12.00–22.00 | Senin 12.00–22.00 | Selasa 12.00–22.00
11,Bakmi Surabaya cak zun,Rabu 16.00–23.30 | Kamis 16.00–23.30 | Jumat 16.00–23.30 | Sabtu 16.00–23.30 | Minggu 16.00–23.30 | Senin 16.00–23.30 | Selasa 16.00–23.30
12,Bakmi Jowo Mas Agus,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00
13,Bakmie Pak Wi',Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00
14,Bakmie Surabaya Mas Nopi,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00
15,Bakmi Jowo Mas Agus,Rabu 17.00–02.00 | Kamis 17.00–02.00 | Jumat 17.00–02.00 | Sabtu 17.00–02.00 | Minggu 17.00–02.00 | Senin 17.00–02.00 | Selasa 17.00–02.00
16,Mie Ayam Lada Hitam Si Jonti,Rabu 09.00–20.00 | Kamis 09.00–20.00 | Jumat 09.00–20.00 | Sabtu 09.00–20.00 | Minggu 09.00–20.00 | Senin 09.00–20.00 | Selasa 09.00–20.00
17,BAKMI JOWO KANG DOEL,Rabu 15.30–23.30 | Kamis 15.30–23.30 | Jumat 15.30–23.30 | Sabtu 15.30–23.30 | Minggu 15.30–23.30 | Senin 15.30–23.30 | Selasa 15.30–23.30
18,BAKMI JOWO GM GAJAH MAKMUR,Rabu 10.00–02.00 | Kamis 10.00–02.00 | Jumat 10.00–02.00 | Sabtu 10.00–02.00 | Minggu 10.00–02.00 | Senin 10.00–02.00 | Selasa 10.00–02.00
19,Mie Ayam Happy,Rabu 10.00–21.00 | Kamis 10.00–21.00 | Jumat 10.00–21.00 | Sabtu 10.00–21.00 | Minggu 10.00–21.00 | Senin Tutup | Selasa 10.00–21.00

Filter data yang bukan di kec Tembalang

In [66]:
df_clean_raw[
    ~df_clean_raw["alamat"].str.contains(
        "Tembalang",
        case=False,
        na=False
    )
][["nama_tempat", "alamat"]]

,nama_tempat,alamat
0,Bakmi Serangkai Tembalang,"Jl. Mulawarman Raya No.11, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50264"
88,Kedai Tinari,"Jl. Sawunggaling III No.44, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268"
118,Nara Ramen Semarang & Waroeng Tokyo,"Jl. Jatimulyo No.12, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268"
123,Joffi Ramen Durian Raya Semarang,"Ruko Durian. 71, Jl. Durian Raya No.RT 08, RW I, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268"
127,Shojin Ramen & Udon Semarang,"Jl. Wolter Monginsidi No.645, Pedurungan Tengah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50192"
132,Shojin Ramen & Udon Kelud Semarang,"Jl. Kelud Raya No.32a, Sampangan, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50327"
134,Golden Geisha Semarang,"Jl. Gajahmada No.123, Pekunden, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50134"
137,Ramen Kakek Jepang,"Jl. Tirto Usodo Tim. No.44, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268"
138,KUROGI,"Jl. Ahmad Yani No.167 A lantai 2, Pleburan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50241"
139,Jojo Ramen,"Jalan Bukit Sari Raya No. R-9, Sumurboto, Banyumanik, Ngesrep, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50269"
142,Nabezo Ramen Dios,"2F93+5FH pujasera) depan Kampus USM, Jl. Malangsari Raya, Tlogosari Kulon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50196"
151,Hakeru Ramen And Bento,"Jl. Sriwijaya No.51a, Wonodri, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50242"
152,Hakata Ikkousha Semarang,"Jl. Karang Anyar No.53, Brumbungan, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50135"
153,Wasabi Sushi & Ramen,"Jl. Mgr Sugiyopranoto No.23, Bulustalan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50245"

In [67]:
df_clean_raw = df_clean_raw[
    df_clean_raw["alamat"].str.contains(
        "Tembalang",
        case=False,
        na=False
    )
].copy()

print("Jumlah data setelah validasi wilayah:", len(df_clean_raw))

Jumlah data setelah validasi wilayah: 125

Hapus data yang bukan bakmi/ramen

In [68]:
pd.set_option("display.max_rows", 200)

display(
    df_clean_raw[["nama_tempat", "jenis_bisnis"]]
    .sort_values("nama_tempat")
)

,nama_tempat,jenis_bisnis
42,(MUBAL) Mie Ayam Bumbu Bali Tembalang,Disimpan
107,Aspro Mie Ayam Wonogiri,Restoran Mie
87,BAKMI DD,Rumah Makan
18,BAKMI JOWO GM GAJAH MAKMUR,Restoran
17,BAKMI JOWO KANG DOEL,Restoran Mie
36,"BAKMI SUROBOYO MAS NDUT (YUDI),METESEH",Restoran Mie
37,BAKMIE SURABAYA CAK BAGUS GROUP,Restoran Mie
64,"BAKSO & MIE AYAM ""PREMIER"" UNDIP",Restoran Bakso
1,BAKSU (Bakmie & Katsu),Restoran Mie
101,Bakmi & Nasgor Mas Hendrik,NaN
108,Bakmi & Nasi goreng Pak Ndut Sendangguwo,NaN
8,Bakmi Dan Nasi Goreng Cak Budi,Restoran Nasi Goreng
104,Bakmi Djowo 14,Restoran
105,"Bakmi Jawa ""Mbah No""",NaN
112,Bakmi Jawa Mas Aris (Solo),NaN
78,"Bakmi Jowo ""RiLEX"" Nasi Goreng",Restoran Nasi Goreng
100,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""",NaN
50,Bakmi Jowo Bu Hadi,Restoran Mie
12,Bakmi Jowo Mas Agus,Restoran Mie
15,Bakmi Jowo Mas Agus,Restoran Mie
58,Bakmi Jowo Mas Jon,Restoran Mie
55,Bakmi Jowo Mas Nang,Restoran Mie
44,Bakmi Jowo Mas Ndut,Restoran Mie
53,Bakmi Jowo Nasi Goreng KADONG TRESNO,Restoran Mie
32,Bakmi Jowo Pak Brewok,Restoran Mie
45,Bakmi Jowo Pak Gito,Restoran Mie
66,Bakmi Jowo Pak Harno,Restoran Mie
71,Bakmi Jowo Pak No,Restoran Mie
76,Bakmi Jowo Pak Sis - Meteseh,Restoran Mie
61,Bakmi Jowo Pak Waris 2,Restoran Mie
73,Bakmi Jowo Pak triss,Restoran Keluarga
54,Bakmi Jowo Risqi,Restoran Mie
65,Bakmi Jowo Sederhana,Restoran Mie
63,Bakmi Jowo Solo,NaN
69,Bakmi Jowo mas Karyo,Restoran Mie
4,Bakmi Juned,Restoran Mie
27,Bakmi Kongsian,Rumah Makan
59,Bakmi Nyemek Keluarga,Restoran Mie
34,Bakmi Surabaya,Restoran Mie
25,"Bakmi Surabaya ""cak Pri""",Restoran Mie
7,Bakmi Surabaya Cak Baron,Restoran Mie
2,Bakmi Surabaya Cak Dul 2,Restoran Mie
11,Bakmi Surabaya cak zun,Restoran Mie
68,"Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275",Restoran
81,Bakmi dan Nasi Goreng Pak Har,Restoran
48,Bakmi jowo Petruk,Restoran Mie
49,Bakmi jowo dan nasi goreng bintang lima,Restoran Nasi Goreng
57,Bakmi jowo pak wito,Restoran Asia
89,Bakmi jowo seger,Disimpan
67,Bakmi surabaya mas gondrong,NaN
5,"Bakmie Jowo ""Mas Anto""",Restoran Mie
29,Bakmie Jowo Mas Jenggot,Restoran Mie
13,Bakmie Pak Wi',Restoran Mie
14,Bakmie Surabaya Mas Nopi,Restoran Mie
10,Bakmie Suroboyo,Restoran Mie
83,Bakso & Mie Ayam PRASOJO,Restoran cepat saji
114,Bakso Beranak & Mie Ayam Bang Jarwo,Restoran Mie
98,Bakso Daging Sapi & Mie Ayam Bang Satrio,Restoran Mie
99,Bakso Dan Mie Ayam Sadam,Disimpan
110,Bakso Mie Ayam Adiroso Tembalang,Lihat foto
126,Enake Japanese Food Kedungmundu,Restoran Jepang
150,Jajalo,Restoran Jepang
124,Joffi Ramen Sambiroto,Restoran Ramen
70,Kedai Mie Aceh Pidie 2018,Restoran Mie
23,Mie Aceh Bang Wali,Restoran Mie
60,Mie Aceh Jambo aye,Restoran Mie
96,"Mie Ayam & Bakso ""Sadam""",Restoran Indonesia
79,Mie Ayam & Bakso (Mibuli) Pak Rudi,Restoran Mie
74,"Mie Ayam & Bakso Barokah pak ndut""Wong Wonogiri""",Restoran Mie
94,Mie Ayam 19,Restoran Mie
56,Mie Ayam 99 Fatmawati,Restoran Mie
102,Mie Ayam Bakso Bu Rini Sirojudin,Restoran Bakso
111,Mie Ayam Bakso Pak Ndut,Restoran Bakso
97,Mie Ayam Bakso Tunggal Rasa,Restoran Bakso
91,Mie Ayam Bang As'ad Tirto Agung Tembalang,Kedai Sarapan & Makan Siang
82,Mie Ayam Cakar Dan Bakso Dosis,Restoran Bakso
106,Mie Ayam Ceker bakso urat dan halus tunggal rasa pak gondo,Restoran Mie
19,Mie Ayam Happy,Restoran Mie
3,Mie Ayam Jakarta Bang Mail,Restoran Mie
16,Mie Ayam Lada Hitam Si Jonti,Restoran Mie
109,Mie Ayam Mbak Mur,Restoran Mie
116,Mie Ayam Mulawarman Pak Radi,Restoran Indonesia
51,Mie Ayam Pak Jumali,Restoran Mie
52,Mie Ayam Pangsit Babaliyut,Lihat foto
46,Mie Ayam Sakti,Restoran Mie
33,Mie Ayam dan Bakso Mas Gondrong,Restoran Bakso
47,Mie Bandung Gg. Belakang Pak Min,Restoran Mie
41,Mie Fil Fil & Cuanki Tembalang,Restoran Mie
28,Mie Goceng Semarang,Restoran Mie
72,Mie Kopyok dan Mie Ayam Seger Pak Tris,Restoran Mie
149,Mie Nges Nges,Restoran Mie
145,Mie Ramen 77,NaN
6,Mie Surabaya Cak Bagus Ketileng,Restoran Mie
122,Mizu Ramen,Restoran Mie
120,Nagoya Ramen & Sushi,Restoran Jepang
117,Nasgor dan bakmi Jawa sidodadi,Rumah Makan
62,Nasi Goreng & Bakmi Jawa (Graha Metro),Restoran
103,Nasi Goreng & Bakmi Jawa Manggala,Restoran
92,Nasi Goreng dan Bakmi Jowo Doa Ibu,Restoran Nasi Goreng
130,Nori House,Restoran
22,PONDOK Bakmi Surabaya Cak DUL,Warung Makanan Kecil
128,Pak MOE Katsu dan Mie Ramen,Restoran
43,Pondok Bakmi Bu Tarno,Kafe
77,Pondok Bakmi Jowo Siper,Restoran
80,Pondok Bakmi Surabaya Cakdul Meteseh,NaN
26,Pondok Nasi Goreng dan Mie,Restoran Nasi Goreng
115,Pondok bakmi pak is,Restoran
121,RAMENDOMI TEMBALANG,Toko Makanan Jepang
144,RYORI JAPANESE FOOD,Restoran
31,Raja Murah (Penyet & Mie Jawa),Restoran Mie
125,SHOYU JAPANESE FOOD - KLIPANG,Restoran Jepang
113,Stay With Mie - Story #1 Sambiroto,Restoran cepat saji
129,"Takoyaki Pekoo Pekoo, Unimus",Restoran Jepang
143,Tower Cafe Semarang,Restoran Asia
9,WARPAD Yamien & Ayam goreng,Kedai Sarapan & Makan Siang
38,WR Rizqi 99/ Mie Ayam Jakarta 99,Restoran
119,Waroeng Tokyo - Tembalang Semarang,Restoran
86,Warung Bakmi Dan Nasi Goreng Mas MR,Restoran cepat saji
95,Warung Bakmi Jowo Mas Tri,NaN
131,Warung Katsu J-pan,Restoran Jepang
75,Warung TUMAN - Nasi Goreng & Bakmi Tuman,Restoran Nasi Goreng
135,Warung Wasabi,Restoran Jepang
133,YOHIKI MIE AYAM,Restoran
136,Yuyake Ramen Ketileng,Restoran Jepang
141,kedai raisu tembalang,Restoran Jepang

In [69]:
keywords_mie = (
    r"bakmi|bakmie|ramen|"
    r"mie jawa|bakmi jawa"
)

cek_relevansi = df_clean_raw[
    df_clean_raw["nama_tempat"]
    .str.contains(keywords_mie, case=False, na=False)
]

print("Data yang terindikasi relevan:", len(cek_relevansi))
print("Total data:", len(df_clean_raw))

Data yang terindikasi relevan: 72
Total data: 125

In [71]:
tidak_relevan = df_clean_raw[
    ~df_clean_raw["nama_tempat"].str.contains(
        keywords_mie,
        case=False,
        na=False
    )
]

tidak_relevan[["nama_tempat", "jenis_bisnis"]]

,nama_tempat,jenis_bisnis
3,Mie Ayam Jakarta Bang Mail,Restoran Mie
6,Mie Surabaya Cak Bagus Ketileng,Restoran Mie
9,WARPAD Yamien & Ayam goreng,Kedai Sarapan & Makan Siang
16,Mie Ayam Lada Hitam Si Jonti,Restoran Mie
19,Mie Ayam Happy,Restoran Mie
23,Mie Aceh Bang Wali,Restoran Mie
26,Pondok Nasi Goreng dan Mie,Restoran Nasi Goreng
28,Mie Goceng Semarang,Restoran Mie
33,Mie Ayam dan Bakso Mas Gondrong,Restoran Bakso
38,WR Rizqi 99/ Mie Ayam Jakarta 99,Restoran
41,Mie Fil Fil & Cuanki Tembalang,Restoran Mie
42,(MUBAL) Mie Ayam Bumbu Bali Tembalang,Disimpan
46,Mie Ayam Sakti,Restoran Mie
47,Mie Bandung Gg. Belakang Pak Min,Restoran Mie
51,Mie Ayam Pak Jumali,Restoran Mie
52,Mie Ayam Pangsit Babaliyut,Lihat foto
56,Mie Ayam 99 Fatmawati,Restoran Mie
60,Mie Aceh Jambo aye,Restoran Mie
64,"BAKSO & MIE AYAM ""PREMIER"" UNDIP",Restoran Bakso
70,Kedai Mie Aceh Pidie 2018,Restoran Mie
72,Mie Kopyok dan Mie Ayam Seger Pak Tris,Restoran Mie
74,"Mie Ayam & Bakso Barokah pak ndut""Wong Wonogiri""",Restoran Mie
79,Mie Ayam & Bakso (Mibuli) Pak Rudi,Restoran Mie
82,Mie Ayam Cakar Dan Bakso Dosis,Restoran Bakso
83,Bakso & Mie Ayam PRASOJO,Restoran cepat saji
91,Mie Ayam Bang As'ad Tirto Agung Tembalang,Kedai Sarapan & Makan Siang
94,Mie Ayam 19,Restoran Mie
96,"Mie Ayam & Bakso ""Sadam""",Restoran Indonesia
97,Mie Ayam Bakso Tunggal Rasa,Restoran Bakso
98,Bakso Daging Sapi & Mie Ayam Bang Satrio,Restoran Mie
99,Bakso Dan Mie Ayam Sadam,Disimpan
102,Mie Ayam Bakso Bu Rini Sirojudin,Restoran Bakso
106,Mie Ayam Ceker bakso urat dan halus tunggal rasa pak gondo,Restoran Mie
107,Aspro Mie Ayam Wonogiri,Restoran Mie
109,Mie Ayam Mbak Mur,Restoran Mie
110,Bakso Mie Ayam Adiroso Tembalang,Lihat foto
111,Mie Ayam Bakso Pak Ndut,Restoran Bakso
113,Stay With Mie - Story #1 Sambiroto,Restoran cepat saji
114,Bakso Beranak & Mie Ayam Bang Jarwo,Restoran Mie
116,Mie Ayam Mulawarman Pak Radi,Restoran Indonesia
119,Waroeng Tokyo - Tembalang Semarang,Restoran
125,SHOYU JAPANESE FOOD - KLIPANG,Restoran Jepang
126,Enake Japanese Food Kedungmundu,Restoran Jepang
129,"Takoyaki Pekoo Pekoo, Unimus",Restoran Jepang
130,Nori House,Restoran
131,Warung Katsu J-pan,Restoran Jepang
133,YOHIKI MIE AYAM,Restoran
135,Warung Wasabi,Restoran Jepang
141,kedai raisu tembalang,Restoran Jepang
143,Tower Cafe Semarang,Restoran Asia
144,RYORI JAPANESE FOOD,Restoran
149,Mie Nges Nges,Restoran Mie
150,Jajalo,Restoran Jepang

In [72]:
nama_tidak_relevan = [
    "Mie Fil Fil & Cuanki Tembalang",
    "WARPAD Yamien & Ayam goreng",
    "Pondok Nasi Goreng dan Mie",
    "YOHIKI MIE AYAM",
    "Waroeng Tokyo - Tembalang Semarang",
    "SHOYU JAPANESE FOOD - KLIPANG",
    "Enake Japanese Food Kedungmundu",
    "Nori House",
    "Mie Nges Nges",
    "Jajalo",
    "Mie Ayam Mulawarman Pak Radi",
    "Bakso Beranak & Mie Ayam Bang Jarwo",
    "Stay With Mie - Story #1 Sambiroto",
    "Mie Ayam Bakso Pak Ndut",
    "Bakso Mie Ayam Adiroso Tembalang",
    "Mie Ayam Mbak Mur",
    "Aspro Mie Ayam Wonogiri",
    "Mie Ayam Ceker bakso urat dan halus tunggal rasa pak gondo",
    "Mie Ayam Bakso Bu Rini Sirojudin",
    "Bakso Dan Mie Ayam Sadam",
    "Bakso Daging Sapi & Mie Ayam Bang Satrio",
    "Mie Ayam Bakso Tunggal Rasa",

    'Mie Ayam & Bakso "Sadam"',

    "Mie Ayam 19",
    "Mie Ayam Bang As'ad Tirto Agung Tembalang",
    "Bakso & Mie Ayam PRASOJO",
    "Mie Ayam Cakar Dan Bakso Dosis",
    "Mie Ayam Cakar Dan Bakso Dosis",
    "Mie Ayam & Bakso (Mibuli) Pak Rudi",

    'Mie Ayam & Bakso Barokah pak ndut"Wong Wonogiri"',

    "Mie Kopyok dan Mie Ayam Seger Pak Tris",
    "Kedai Mie Aceh Pidie 2018",

    'BAKSO & MIE AYAM "PREMIER" UNDIP',

    "Mie Aceh Jambo aye",
    "Mie Ayam 99 Fatmawati",
    "Mie Ayam Pangsit Babaliyut",
    "Mie Ayam Pak Jumali",
    "Mie Ayam Jakarta Bang Mail",
    "Mie Surabaya Cak Bagus Ketileng",
    "Mie Ayam Lada Hitam Si Jonti",
    "Mie Ayam Happy",
    "Mie Aceh Bang Wali",
    "Mie Goceng Semarang",
    "Raja Murah (Penyet & Mie Jawa)",
    "Mie Ayam dan Bakso Mas Gondrong",
    "WR Rizqi 99/ Mie Ayam Jakarta 99",
    "(MUBAL) Mie Ayam Bumbu Bali Tembalang",
    "Mie Ayam Sakti",
    "Mie Bandung Gg. Belakang Pak Min"
]

df_clean_raw = df_clean_raw[
    ~df_clean_raw["nama_tempat"].isin(nama_tidak_relevan)
].copy()

print("Jumlah data setelah menghapus bisnis tidak relevan:", len(df_clean_raw))

Jumlah data setelah menghapus bisnis tidak relevan: 77

CEK MISSING VALUE

In [73]:
missing = pd.DataFrame({
    "jumlah_missing": df_clean_raw.isna().sum(),
    "persentase": (df_clean_raw.isna().mean() * 100).round(2)
}).sort_values("jumlah_missing", ascending=False)

display(missing)

                 jumlah_missing  persentase
website                      77      100.00
harga                        41       53.25
telepon                      22       28.57
jam_operasional              14       18.18
jenis_bisnis                 10       12.99
jumlah_review                 5        6.49
rating                        0        0.00
alamat                        0        0.00
nama_tempat                   0        0.00
jumlah_bintang                0        0.00
latitude                      0        0.00
longitude                     0        0.00
no                            0        0.00

Handle website yang NaN

In [74]:
display(
    df_clean_raw[["nama_tempat", "website"]]
)

,nama_tempat,website
1,BAKSU (Bakmie & Katsu),NaN
2,Bakmi Surabaya Cak Dul 2,NaN
4,Bakmi Juned,NaN
5,"Bakmie Jowo ""Mas Anto""",NaN
7,Bakmi Surabaya Cak Baron,NaN
8,Bakmi Dan Nasi Goreng Cak Budi,NaN
10,Bakmie Suroboyo,NaN
11,Bakmi Surabaya cak zun,NaN
12,Bakmi Jowo Mas Agus,NaN
13,Bakmie Pak Wi',NaN
14,Bakmie Surabaya Mas Nopi,NaN
15,Bakmi Jowo Mas Agus,NaN
17,BAKMI JOWO KANG DOEL,NaN
18,BAKMI JOWO GM GAJAH MAKMUR,NaN
22,PONDOK Bakmi Surabaya Cak DUL,NaN
25,"Bakmi Surabaya ""cak Pri""",NaN
27,Bakmi Kongsian,NaN
29,Bakmie Jowo Mas Jenggot,NaN
32,Bakmi Jowo Pak Brewok,NaN
34,Bakmi Surabaya,NaN
36,"BAKMI SUROBOYO MAS NDUT (YUDI),METESEH",NaN
37,BAKMIE SURABAYA CAK BAGUS GROUP,NaN
43,Pondok Bakmi Bu Tarno,NaN
44,Bakmi Jowo Mas Ndut,NaN
45,Bakmi Jowo Pak Gito,NaN
48,Bakmi jowo Petruk,NaN
49,Bakmi jowo dan nasi goreng bintang lima,NaN
50,Bakmi Jowo Bu Hadi,NaN
53,Bakmi Jowo Nasi Goreng KADONG TRESNO,NaN
54,Bakmi Jowo Risqi,NaN
55,Bakmi Jowo Mas Nang,NaN
57,Bakmi jowo pak wito,NaN
58,Bakmi Jowo Mas Jon,NaN
59,Bakmi Nyemek Keluarga,NaN
61,Bakmi Jowo Pak Waris 2,NaN
62,Nasi Goreng & Bakmi Jawa (Graha Metro),NaN
63,Bakmi Jowo Solo,NaN
65,Bakmi Jowo Sederhana,NaN
66,Bakmi Jowo Pak Harno,NaN
67,Bakmi surabaya mas gondrong,NaN
68,"Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275",NaN
69,Bakmi Jowo mas Karyo,NaN
71,Bakmi Jowo Pak No,NaN
73,Bakmi Jowo Pak triss,NaN
75,Warung TUMAN - Nasi Goreng & Bakmi Tuman,NaN
76,Bakmi Jowo Pak Sis - Meteseh,NaN
77,Pondok Bakmi Jowo Siper,NaN
78,"Bakmi Jowo ""RiLEX"" Nasi Goreng",NaN
80,Pondok Bakmi Surabaya Cakdul Meteseh,NaN
81,Bakmi dan Nasi Goreng Pak Har,NaN
86,Warung Bakmi Dan Nasi Goreng Mas MR,NaN
87,BAKMI DD,NaN
89,Bakmi jowo seger,NaN
92,Nasi Goreng dan Bakmi Jowo Doa Ibu,NaN
95,Warung Bakmi Jowo Mas Tri,NaN
100,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""",NaN
101,Bakmi & Nasgor Mas Hendrik,NaN
103,Nasi Goreng & Bakmi Jawa Manggala,NaN
104,Bakmi Djowo 14,NaN
105,"Bakmi Jawa ""Mbah No""",NaN
108,Bakmi & Nasi goreng Pak Ndut Sendangguwo,NaN
112,Bakmi Jawa Mas Aris (Solo),NaN
115,Pondok bakmi pak is,NaN
117,Nasgor dan bakmi Jawa sidodadi,NaN
120,Nagoya Ramen & Sushi,NaN
121,RAMENDOMI TEMBALANG,NaN
122,Mizu Ramen,NaN
124,Joffi Ramen Sambiroto,NaN
128,Pak MOE Katsu dan Mie Ramen,NaN
129,"Takoyaki Pekoo Pekoo, Unimus",NaN
131,Warung Katsu J-pan,NaN
135,Warung Wasabi,NaN
136,Yuyake Ramen Ketileng,NaN
141,kedai raisu tembalang,NaN
143,Tower Cafe Semarang,NaN
144,RYORI JAPANESE FOOD,NaN
145,Mie Ramen 77,NaN

In [75]:
df_clean_raw = df_clean_raw.drop(columns=["website"])

In [76]:
display(df_clean_raw.head())

,nama_tempat,alamat,jenis_bisnis,rating,jumlah_bintang,jumlah_review,jam_operasional,harga,latitude,longitude,telepon,no
1,BAKSU (Bakmie & Katsu),"Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Restoran Mie,4.3,5,144.0,Rabu 09.00–21.00 | Kamis 09.00–21.00 | Jumat 09.00–21.00 | Sabtu 09.00–21.00 | Minggu 09.00–21.00 | Senin 09.00–21.00 | Selasa 09.00–21.00,Rp 1–25.000,-7.057076,110.444335,0895-3605-97975,2
2,Bakmi Surabaya Cak Dul 2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran Mie,4.0,5,495.0,Rabu 07.30–23.30 | Kamis 07.30–23.30 | Jumat 07.30–23.30 | Sabtu 07.30–23.30 | Minggu 07.30–23.30 | Senin 07.30–23.30 | Selasa 07.30–23.30,Rp 1–25.000,-7.068204,110.437274,0821-3400-6730,3
4,Bakmi Juned,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.7,5,158.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu Tutup | Senin Tutup | Selasa 17.00–00.00,Rp 1–25.000,-7.024015,110.458790,NaN,5
5,"Bakmie Jowo ""Mas Anto""","Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.5,5,61.0,Rabu 17.30–00.00 | Kamis Tutup | Jumat 17.30–00.00 | Sabtu 17.30–00.00 | Minggu 17.30–00.00 | Senin 17.30–00.00 | Selasa 17.30–00.00,NaN,-7.024459,110.473755,0896-6801-4356,6
7,Bakmi Surabaya Cak Baron,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,27.0,Rabu 18.45–23.45 | Kamis 18.45–23.45 | Jumat 18.45–23.45 | Sabtu 18.45–23.45 | Minggu 18.45–23.45 | Senin 18.45–23.45 | Selasa 18.45–23.45,NaN,-7.029325,110.468078,NaN,8

Handel harga yang NaN

In [77]:
harga_kosong = df_clean_raw[
    df_clean_raw["harga"].isna()
][["nama_tempat", "alamat", "harga"]].reset_index(drop=True)

display(harga_kosong)

,nama_tempat,alamat,harga
0,"Bakmie Jowo ""Mas Anto""","Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
1,Bakmi Surabaya Cak Baron,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
2,Bakmie Suroboyo,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
3,Bakmi Jowo Mas Agus,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
4,Bakmie Surabaya Mas Nopi,"Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN
5,Bakmi Jowo Mas Agus,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",NaN
6,BAKMI JOWO KANG DOEL,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN
7,PONDOK Bakmi Surabaya Cak DUL,"WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
8,Bakmi Surabaya,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
9,"BAKMI SUROBOYO MAS NDUT (YUDI),METESEH","Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
10,Bakmi Jowo Risqi,"Jl. Bougenville Dalam No.Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
11,Bakmi jowo pak wito,"Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
12,Bakmi Nyemek Keluarga,"Perum Jl. Wanamukti No.16 Blok E4, Sambiroto, Tembalang, Semarang City, Central Java 50276",NaN
13,Bakmi Jowo Solo,"Jl. Tulus Harapan No.4 Blk C, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
14,Bakmi Jowo Sederhana,"Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
15,Bakmi surabaya mas gondrong,"Klipang blok R 7 No.7, RT.05/RW.06, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
16,"Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275","WCQQ+M8C, Gg. Nirwana Sari I, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
17,Bakmi Jowo Pak No,"XFG6+25P, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",NaN
18,Bakmi Jowo Pak triss,"XFQ3+RXP, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
19,Warung TUMAN - Nasi Goreng & Bakmi Tuman,"Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
20,Bakmi Jowo Pak Sis - Meteseh,"Jl. Bukit Klp. Gading I No.32, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
21,Pondok Bakmi Jowo Siper,"Jl. kd.mundu No.12, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",NaN
22,"Bakmi Jowo ""RiLEX"" Nasi Goreng","Jalan Kedung Mundu Raya No.23B, Sambiroto, Tembalang, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN
23,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
24,Bakmi dan Nasi Goreng Pak Har,"WCMP+5WR, Jl. Mulawarman Raya, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
25,BAKMI DD,"Jl. Gondang Raya No.16, RT.3/RW.1, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
26,Bakmi jowo seger,"XFP2+M5R, Jl. Kedungmundu, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
27,Nasi Goreng dan Bakmi Jowo Doa Ibu,"Jl. Sambiroto Raya No.82-80, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",NaN
28,Warung Bakmi Jowo Mas Tri,"Jl. Gondang Raya No.5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
29,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""","Jl. Banjarsari Selatan No.51-55, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268",NaN
30,Bakmi & Nasgor Mas Hendrik,"Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
31,Nasi Goreng & Bakmi Jawa Manggala,"Jl. Bukit Bougenvil Raya No.8, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
32,Bakmi Djowo 14,"Jl. Sendang Dahlia No.10, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
33,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
34,Bakmi & Nasi goreng Pak Ndut Sendangguwo,"XFM4+76V, Jl. Sendangguwo Selatan Baru II, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
35,Bakmi Jawa Mas Aris (Solo),"XF89+J2V, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
36,Nasgor dan bakmi Jawa sidodadi,"XFP2+H65, Jl. Kedungmundu, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN
37,Pak MOE Katsu dan Mie Ramen,"Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
38,kedai raisu tembalang,"perum aldi griya permai Jl. Bulusan Sel. No.27, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
39,RYORI JAPANESE FOOD,"XFM9+7R5, Jl. Pandan Wangi Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
40,Mie Ramen 77,"WCQW+M56, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN

Handel Jam operasional yang NaN

In [78]:
harga_kosong = df_clean_raw[
    df_clean_raw["jam_operasional"].isna()
][["nama_tempat", "alamat", "jam_operasional"]].reset_index(drop=True)

display(harga_kosong)

,nama_tempat,alamat,jam_operasional
0,Bakmi Kongsian,"Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
1,Bakmie Jowo Mas Jenggot,"Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
2,BAKMIE SURABAYA CAK BAGUS GROUP,"WFVC+7CQ, Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
3,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
4,Warung Bakmi Dan Nasi Goreng Mas MR,"WCPV+66W, Jl. Gondang Timur IV, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
5,Warung Bakmi Jowo Mas Tri,"Jl. Gondang Raya No.5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
6,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""","Jl. Banjarsari Selatan No.51-55, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268",NaN
7,Bakmi & Nasgor Mas Hendrik,"Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
8,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
9,Pondok bakmi pak is,"Jl. Gendong Raya No.126, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
10,Joffi Ramen Sambiroto,"Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah",NaN
11,Warung Wasabi,"Jalan Tirto Agung No. 77 Pedalangan Tembalang, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268",NaN
12,Yuyake Ramen Ketileng,"Jl. Ketileng Raya No.15, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
13,Mie Ramen 77,"WCQW+M56, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN

In [79]:
# Melengkapi jam operasional berdasarkan hasil pengecekan manual

df_clean_raw.loc[
    df_clean_raw["nama_tempat"] == "Joffi Ramen Sambiroto",
    "jam_operasional"
] = (
    "Kamis 10.00–22.00 | Jumat 10.00–22.00 | "
    "Sabtu 10.00–22.00 | Minggu 10.00–22.00 | "
    "Senin 10.00–22.00 | Selasa 10.00–22.00 | "
    "Rabu 10.00–22.00"
)

df_clean_raw.loc[
    df_clean_raw["nama_tempat"] == "Stay With Mie - Story #1 Sambiroto",
    "jam_operasional"
] = (
    "Kamis 11.00–21.00 | Jumat 11.00–21.00 | "
    "Sabtu 11.00–21.00 | Minggu 11.00–21.00 | "
    "Senin 11.00–21.00 | Selasa 11.00–21.00 | "
    "Rabu 11.00–21.00"
)

df_clean_raw.loc[
    df_clean_raw["nama_tempat"] == "Mie Aceh Jambo aye",
    "jam_operasional"
] = (
    "Kamis 10.00–22.00 | Jumat 10.00–22.00 | "
    "Sabtu 10.00–22.00 | Minggu 10.00–22.00 | "
    "Senin 10.00–22.00 | Selasa 10.00–22.00 | "
    "Rabu 10.00–22.00"
)

df_clean_raw.loc[
    df_clean_raw["nama_tempat"] == "Mie Ayam Pangsit Babaliyut",
    "jam_operasional"
] = (
    "Kamis 10.30–22.00 | Jumat 10.30–22.00 | "
    "Sabtu 10.30–22.00 | Minggu 10.30–22.00 | "
    "Senin 10.30–22.00 | Selasa 10.30–22.00 | "
    "Rabu 10.30–22.00"
)

# Status berdasarkan pengecekan manual
df_clean_raw.loc[
    df_clean_raw["nama_tempat"].isin([
        "Warung Bakmi Jowo Mas Tri",
        'Bakmi Jowo & Nasi Goreng "Kang Gepeng"',
        "Bakmi & Nasgor Mas Hendrik",
        "Mie Ramen 77"
    ]),
    "jam_operasional"
] = "Tutup permanen"

df_clean_raw.loc[
    df_clean_raw["nama_tempat"].isin([
        "Yuyake Ramen Ketileng",
        "Warung Wasabi"
    ]),
    "jam_operasional"
] = "Tutup sementara"

# Bisnis yang tidak memiliki informasi jam buka
df_clean_raw.loc[
    df_clean_raw["nama_tempat"].isin([
        "Bakmi Kongsian",
        "Bakmie Jowo Mas Jenggot",
        "BAKMIE SURABAYA CAK BAGUS GROUP",
        "Pondok Bakmi Surabaya Cakdul Meteseh",
        "Warung Bakmi Dan Nasi Goreng Mas MR",
        'Bakmi Jawa "Mbah No"',
        "Pondok bakmi pak is"
    ]),
    "jam_operasional"
] = "Tidak ada info jam buka"

In [80]:
print("Missing jam operasional:", df_clean_raw["jam_operasional"].isna().sum())

Missing jam operasional: 0

Handel jumlah review yang kosong

In [82]:
harga_kosong = df_clean_raw[
    df_clean_raw["jumlah_review"].isna()
][["nama_tempat", "alamat", "jumlah_review"]].reset_index(drop=True)

display(harga_kosong)

,nama_tempat,alamat,jumlah_review
0,"Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275","WCQQ+M8C, Gg. Nirwana Sari I, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
1,Bakmi Djowo 14,"Jl. Sendang Dahlia No.10, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
2,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
3,Bakmi Jawa Mas Aris (Solo),"XF89+J2V, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
4,Nasgor dan bakmi Jawa sidodadi,"XFP2+H65, Jl. Kedungmundu, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN

Handel jenis bisnis yang kosong

In [83]:
harga_kosong = df_clean_raw[
    df_clean_raw["jenis_bisnis"].isna()
][["nama_tempat", "alamat", "jenis_bisnis"]].reset_index(drop=True)

display(harga_kosong)

,nama_tempat,alamat,jenis_bisnis
0,Bakmi Jowo Solo,"Jl. Tulus Harapan No.4 Blk C, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
1,Bakmi surabaya mas gondrong,"Klipang blok R 7 No.7, RT.05/RW.06, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
2,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
3,Warung Bakmi Jowo Mas Tri,"Jl. Gondang Raya No.5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
4,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""","Jl. Banjarsari Selatan No.51-55, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268",NaN
5,Bakmi & Nasgor Mas Hendrik,"Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
6,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
7,Bakmi & Nasi goreng Pak Ndut Sendangguwo,"XFM4+76V, Jl. Sendangguwo Selatan Baru II, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
8,Bakmi Jawa Mas Aris (Solo),"XF89+J2V, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
9,Mie Ramen 77,"WCQW+M56, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN

In [84]:
# Melengkapi jenis bisnis berdasarkan pengecekan manual

jenis_bisnis_manual = {
    "Bakmi Jowo Solo": "Restoran Mie",
    "Bakmi surabaya mas gondrong": "Warung nasi",
    "Pondok Bakmi Surabaya Cakdul Meteseh": "Restoran Indonesia",
    "Warung Bakmi Jowo Mas Tri": "Restoran Indonesia",
    'Bakmi Jowo & Nasi Goreng "Kang Gepeng"': "Tutup permanen",
    "Bakmi & Nasgor Mas Hendrik": "Tutup permanen",
    'Bakmi Jawa "Mbah No"': "Restoran Mie",
    "Bakmi & Nasi goreng Pak Ndut Sendangguwo": "Restoran",
    "Bakmi Jawa Mas Aris (Solo)": "Restoran Mie",
    "Mie Ramen 77": "Tutup permanen"
}

for nama, jenis in jenis_bisnis_manual.items():
    df_clean_raw.loc[
        df_clean_raw["nama_tempat"] == nama,
        "jenis_bisnis"
    ] = jenis

In [86]:
df_clean_raw[df_clean_raw["nama_tempat"].isin(jenis_bisnis_manual.keys())][
    ["nama_tempat", "jenis_bisnis"]
]

                                  nama_tempat        jenis_bisnis
63                            Bakmi Jowo Solo        Restoran Mie
67                Bakmi surabaya mas gondrong         Warung nasi
80       Pondok Bakmi Surabaya Cakdul Meteseh  Restoran Indonesia
95                  Warung Bakmi Jowo Mas Tri  Restoran Indonesia
100    Bakmi Jowo & Nasi Goreng "Kang Gepeng"      Tutup permanen
101                Bakmi & Nasgor Mas Hendrik      Tutup permanen
105                      Bakmi Jawa "Mbah No"        Restoran Mie
108  Bakmi & Nasi goreng Pak Ndut Sendangguwo            Restoran
112                Bakmi Jawa Mas Aris (Solo)        Restoran Mie
145                              Mie Ramen 77      Tutup permanen

Handel telepon yg kosong

In [87]:
harga_kosong = df_clean_raw[
    df_clean_raw["telepon"].isna()
][["nama_tempat", "alamat", "telepon"]].reset_index(drop=True)

display(harga_kosong)

,nama_tempat,alamat,telepon
0,Bakmi Juned,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",NaN
1,Bakmi Surabaya Cak Baron,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
2,Bakmie Suroboyo,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
3,Bakmi Kongsian,"Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
4,Bakmie Jowo Mas Jenggot,"Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
5,Pondok Bakmi Bu Tarno,"XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Tembalang, Semarang City, Central Java 50273",NaN
6,Bakmi Jowo Mas Ndut,"Jl. Dinar Elok Raya No.K2 No.5, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
7,Bakmi Jowo Mas Nang,"perum klipang Blk. P XIV, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN
8,Bakmi Jowo Mas Jon,"XF2H+RJR, Bundaran Simpang 4 Jl. Klipang, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN
9,Bakmi Jowo Sederhana,"Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
10,Bakmi Jowo Pak Harno,"WFQ7+R2R, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
11,Bakmi Jowo mas Karyo,"XF99+X3F, Jl. Wanamukti, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",NaN
12,Warung TUMAN - Nasi Goreng & Bakmi Tuman,"Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
13,"Bakmi Jowo ""RiLEX"" Nasi Goreng","Jalan Kedung Mundu Raya No.23B, Sambiroto, Tembalang, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",NaN
14,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
15,Bakmi dan Nasi Goreng Pak Har,"WCMP+5WR, Jl. Mulawarman Raya, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
16,Bakmi jowo seger,"XFP2+M5R, Jl. Kedungmundu, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",NaN
17,Warung Bakmi Jowo Mas Tri,"Jl. Gondang Raya No.5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN
18,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""","Jl. Banjarsari Selatan No.51-55, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268",NaN
19,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",NaN
20,Joffi Ramen Sambiroto,"Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah",NaN
21,Warung Katsu J-pan,"Jl. Banjarsari No.29, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",NaN

In [88]:
# Melengkapi nomor telepon berdasarkan pengecekan manual

df_clean_raw.loc[
    df_clean_raw["nama_tempat"] == "Pondok Bakmi Bu Tarno",
    "telepon"
] = "085287830644"

df_clean_raw.loc[
    df_clean_raw['nama_tempat'] == 'Bakmi Jowo & Nasi Goreng "Kang Gepeng"',
    "telepon"
] = "Tutup permanen"

In [89]:
df_clean_raw[
    df_clean_raw["nama_tempat"].isin([
        "Pondok Bakmi Bu Tarno",
        'Bakmi Jowo & Nasi Goreng "Kang Gepeng"'
    ])
][["nama_tempat", "telepon"]]

                                nama_tempat         telepon
43                    Pondok Bakmi Bu Tarno    085287830644
100  Bakmi Jowo & Nasi Goreng "Kang Gepeng"  Tutup permanen

EXTRACT KECAMATAN DAN KELURAHAN

In [90]:
display(
    df_clean_raw["alamat"].head(20)
)

1                                     Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277
2                              Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278
4                                             Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276
5                                    Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273
7                              XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
8                                       Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276
10                                   XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273
11                               Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
12                               XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
13                              XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273
14                            Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274
15                                    Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276
17                                                 XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274
18                            Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248
22                               WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277
25                 Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
27    Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271
29                                  Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
32                        Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272
34             Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271
Name: alamat, dtype: object

In [91]:
df_clean_raw["kecamatan"] = (
    df_clean_raw["alamat"]
    .str.extract(r"Kec\.\s*([^,]+)", expand=False)
    .str.strip()
)

display(
    df_clean_raw[["alamat", "kecamatan"]].head(20)
)

,alamat,kecamatan
1,"Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Tembalang
2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Tembalang
4,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Tembalang
5,"Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Tembalang
7,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
8,"Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Tembalang
10,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Tembalang
11,"Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
12,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
13,"XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Tembalang
14,"Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Tembalang
15,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Tembalang
17,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Tembalang
18,"Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248",Tembalang
22,"WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Tembalang
25,"Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
27,"Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Tembalang
29,"Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
32,"Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Tembalang
34,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Tembalang

In [92]:
df_clean_raw["kelurahan"] = (
    df_clean_raw["alamat"]
    .str.extract(r",\s*([^,]+),\s*Kec\.", expand=False)
    .str.strip()
)

display(
    df_clean_raw[["alamat", "kelurahan"]].head(20)
)

,alamat,kelurahan
1,"Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Bulusan
2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Kramas
4,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Kedungmundu
5,"Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Kedungmundu
7,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Sendangmulyo
8,"Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Sambiroto
10,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Kedungmundu
11,"Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Sambiroto
12,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Mangunharjo
13,"XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Kedungmundu
14,"Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Tandang
15,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Sambiroto
17,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Kedungmundu
18,"Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248",Sendangguwo
22,"WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Meteseh
25,"Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Sendangmulyo
27,"Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Meteseh
29,"Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Sendangmulyo
32,"Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Sendangmulyo
34,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Meteseh

In [93]:
df_clean_raw["kelurahan"].isna().sum()

np.int64(7)

In [94]:
kelurahan_kosong = df_clean_raw[
    df_clean_raw["kelurahan"].isna()
][["nama_tempat", "alamat", "kelurahan"]]

display(kelurahan_kosong)

,nama_tempat,alamat,kelurahan
43,Pondok Bakmi Bu Tarno,"XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Tembalang, Semarang City, Central Java 50273",NaN
55,Bakmi Jowo Mas Nang,"perum klipang Blk. P XIV, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN
58,Bakmi Jowo Mas Jon,"XF2H+RJR, Bundaran Simpang 4 Jl. Klipang, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN
59,Bakmi Nyemek Keluarga,"Perum Jl. Wanamukti No.16 Blok E4, Sambiroto, Tembalang, Semarang City, Central Java 50276",NaN
75,Warung TUMAN - Nasi Goreng & Bakmi Tuman,"Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",NaN
101,Bakmi & Nasgor Mas Hendrik,"Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",NaN
124,Joffi Ramen Sambiroto,"Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah",NaN

In [95]:
# Melengkapi kelurahan dari alamat yang tidak memiliki pola "Kec."

kelurahan_manual = {
    "Pondok Bakmi Bu Tarno": "Kedungmundu",
    "Bakmi Jowo Mas Nang": "Sendangmulyo",
    "Bakmi Jowo Mas Jon": "Sendangmulyo",
    "Bakmi Nyemek Keluarga": "Sambiroto",
    "Warung TUMAN - Nasi Goreng & Bakmi Tuman": "Meteseh",
    "Mie Ayam & Bakso (Mibuli) Pak Rudi": "Kramas",
    "Bakmi & Nasgor Mas Hendrik": "Bulusan",
    "Bakso Mie Ayam Adiroso Tembalang": "Tembalang",
    "Joffi Ramen Sambiroto": "Sambiroto"
}

for nama, kelurahan in kelurahan_manual.items():
    df_clean_raw.loc[
        df_clean_raw["nama_tempat"] == nama,
        "kelurahan"
    ] = kelurahan

In [96]:
df_clean_raw["kelurahan"].isna().sum()

np.int64(0)

In [97]:
df_clean_raw[df_clean_raw["kecamatan"].isna()][
    ["nama_tempat", "alamat", "kecamatan", "kelurahan"]
]

,nama_tempat,alamat,kecamatan,kelurahan
43,Pondok Bakmi Bu Tarno,"XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Tembalang, Semarang City, Central Java 50273",NaN,Kedungmundu
55,Bakmi Jowo Mas Nang,"perum klipang Blk. P XIV, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN,Sendangmulyo
58,Bakmi Jowo Mas Jon,"XF2H+RJR, Bundaran Simpang 4 Jl. Klipang, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",NaN,Sendangmulyo
59,Bakmi Nyemek Keluarga,"Perum Jl. Wanamukti No.16 Blok E4, Sambiroto, Tembalang, Semarang City, Central Java 50276",NaN,Sambiroto

In [98]:
df_clean_raw.loc[
    df_clean_raw["kecamatan"].isna(),
    "kecamatan"
] = "Tembalang"

In [99]:
print("Missing kecamatan:", df_clean_raw["kecamatan"].isna().sum())

Missing kecamatan: 0

STANDARDISASI NAMA KOLOM

In [100]:
df_clean_raw.columns.tolist()

['nama_tempat',
 'alamat',
 'jenis_bisnis',
 'rating',
 'jumlah_bintang',
 'jumlah_review',
 'jam_operasional',
 'harga',
 'latitude',
 'longitude',
 'telepon',
 'no',
 'kecamatan',
 'kelurahan']

In [101]:
# Memastikan nama kolom sudah terstandarisasi

df_clean_raw.columns = (
    df_clean_raw.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df_clean_raw.columns.tolist()

['nama_tempat',
 'alamat',
 'jenis_bisnis',
 'rating',
 'jumlah_bintang',
 'jumlah_review',
 'jam_operasional',
 'harga',
 'latitude',
 'longitude',
 'telepon',
 'no',
 'kecamatan',
 'kelurahan']

SIMPAN DATA CLEANING

In [102]:
# Final checking dataset hasil cleaning

print("Jumlah baris dan kolom:", df_clean_raw.shape)
print("\nNama kolom:")
print(df_clean_raw.columns.tolist())

print("\nMissing values:")
display(
    df_clean_raw.isna().sum().to_frame("jumlah_missing")
)

Jumlah baris dan kolom: (77, 14)

Nama kolom:
['nama_tempat', 'alamat', 'jenis_bisnis', 'rating', 'jumlah_bintang', 'jumlah_review', 'jam_operasional', 'harga', 'latitude', 'longitude', 'telepon', 'no', 'kecamatan', 'kelurahan']

Missing values:

                 jumlah_missing
nama_tempat                   0
alamat                        0
jenis_bisnis                  0
rating                        0
jumlah_bintang                0
jumlah_review                 5
jam_operasional               0
harga                        41
latitude                      0
longitude                     0
telepon                      20
no                            0
kecamatan                     0
kelurahan                     0

In [103]:
# Simpan dataset hasil cleaning ke folder data
output_path = r"D:\LATHIFAH HUSNUN\Work\urbansolv-test\data\clean_data.csv"
df_clean_raw.to_csv(output_path, index=False)
print(f"Dataset berhasil disimpan di:\n{output_path}")

Dataset berhasil disimpan di:
D:\LATHIFAH HUSNUN\Work\urbansolv-test\data\clean_data.csv

In [105]:
# Baca dan tampilkan kembali hasil akhir yang sudah disimpan
df_clean = pd.read_csv(r"D:\LATHIFAH HUSNUN\Work\urbansolv-test\data\clean_data.csv")

print(df_clean.columns.tolist())
print("\nJumlah baris:", len(df_clean))

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

df_clean

['nama_tempat', 'alamat', 'jenis_bisnis', 'rating', 'jumlah_bintang', 'jumlah_review', 'jam_operasional', 'harga', 'latitude', 'longitude', 'telepon', 'no', 'kecamatan', 'kelurahan']

Jumlah baris: 77

,nama_tempat,alamat,jenis_bisnis,rating,jumlah_bintang,jumlah_review,jam_operasional,harga,latitude,longitude,telepon,no,kecamatan,kelurahan
0,BAKSU (Bakmie & Katsu),"Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Restoran Mie,4.3,5,144.0,Rabu 09.00–21.00 | Kamis 09.00–21.00 | Jumat 09.00–21.00 | Sabtu 09.00–21.00 | Minggu 09.00–21.00 | Senin 09.00–21.00 | Selasa 09.00–21.00,Rp 1–25.000,-7.057076,110.444335,0895-3605-97975,2,Tembalang,Bulusan
1,Bakmi Surabaya Cak Dul 2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran Mie,4.0,5,495.0,Rabu 07.30–23.30 | Kamis 07.30–23.30 | Jumat 07.30–23.30 | Sabtu 07.30–23.30 | Minggu 07.30–23.30 | Senin 07.30–23.30 | Selasa 07.30–23.30,Rp 1–25.000,-7.068204,110.437274,0821-3400-6730,3,Tembalang,Kramas
2,Bakmi Juned,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.7,5,158.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu Tutup | Senin Tutup | Selasa 17.00–00.00,Rp 1–25.000,-7.024015,110.458790,NaN,5,Tembalang,Kedungmundu
3,"Bakmie Jowo ""Mas Anto""","Jl. Sinar Waluyo Utara, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.5,5,61.0,Rabu 17.30–00.00 | Kamis Tutup | Jumat 17.30–00.00 | Sabtu 17.30–00.00 | Minggu 17.30–00.00 | Senin 17.30–00.00 | Selasa 17.30–00.00,NaN,-7.024459,110.473755,0896-6801-4356,6,Tembalang,Kedungmundu
4,Bakmi Surabaya Cak Baron,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,27.0,Rabu 18.45–23.45 | Kamis 18.45–23.45 | Jumat 18.45–23.45 | Sabtu 18.45–23.45 | Minggu 18.45–23.45 | Senin 18.45–23.45 | Selasa 18.45–23.45,NaN,-7.029325,110.468078,NaN,8,Tembalang,Sendangmulyo
5,Bakmi Dan Nasi Goreng Cak Budi,"Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Nasi Goreng,4.7,5,138.0,Rabu 12.00–00.00 | Kamis 12.00–00.00 | Jumat 12.00–00.00 | Sabtu 12.00–00.00 | Minggu 12.00–00.00 | Senin 12.00–00.00 | Selasa 12.00–00.00,Rp 1–25.000,-7.034967,110.457842,0877-0025-4333,9,Tembalang,Sambiroto
6,Bakmie Suroboyo,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.6,5,5.0,Rabu 12.00–22.00 | Kamis 12.00–22.00 | Jumat 12.00–22.00 | Sabtu 12.00–22.00 | Minggu 12.00–22.00 | Senin 12.00–22.00 | Selasa 12.00–22.00,NaN,-7.020926,110.471160,NaN,11,Tembalang,Kedungmundu
7,Bakmi Surabaya cak zun,"Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.3,5,44.0,Rabu 16.00–23.30 | Kamis 16.00–23.30 | Jumat 16.00–23.30 | Sabtu 16.00–23.30 | Minggu 16.00–23.30 | Senin 16.00–23.30 | Selasa 16.00–23.30,Rp 1–25.000,-7.027705,110.459498,0857-1312-5010,12,Tembalang,Sambiroto
8,Bakmi Jowo Mas Agus,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,29.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.037619,110.468281,0819-0437-2937,13,Tembalang,Mangunharjo
9,Bakmie Pak Wi',"XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.5,5,44.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,Rp 1–25.000,-7.016084,110.466717,0821-2831-6087,14,Tembalang,Kedungmundu
10,Bakmie Surabaya Mas Nopi,"Jl. Rogojembangan Raya No.147-151, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Mie,5.0,5,7.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.015127,110.448626,0856-3258-158,15,Tembalang,Tandang
11,Bakmi Jowo Mas Agus,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.5,5,99.0,Rabu 17.00–02.00 | Kamis 17.00–02.00 | Jumat 17.00–02.00 | Sabtu 17.00–02.00 | Minggu 17.00–02.00 | Senin 17.00–02.00 | Selasa 17.00–02.00,NaN,-7.032360,110.458110,0858-0213-9915,16,Tembalang,Sambiroto
12,BAKMI JOWO KANG DOEL,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Mie,4.9,5,16.0,Rabu 15.30–23.30 | Kamis 15.30–23.30 | Jumat 15.30–23.30 | Sabtu 15.30–23.30 | Minggu 15.30–23.30 | Senin 15.30–23.30 | Selasa 15.30–23.30,NaN,-7.021003,110.456780,0812-2556-0512,18,Tembalang,Kedungmundu
13,BAKMI JOWO GM GAJAH MAKMUR,"Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248",Restoran,4.9,5,30.0,Rabu 10.00–02.00 | Kamis 10.00–02.00 | Jumat 10.00–02.00 | Sabtu 10.00–02.00 | Minggu 10.00–02.00 | Senin 10.00–02.00 | Selasa 10.00–02.00,Rp 1–25.000,-7.007305,110.448846,0823-2276-4326,19,Tembalang,Sendangguwo
14,PONDOK Bakmi Surabaya Cak DUL,"WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Warung Makanan Kecil,3.9,5,14.0,Rabu 16.00–23.00 | Kamis 16.00–23.00 | Jumat 16.00–23.00 | Sabtu 16.00–23.00 | Minggu 16.00–23.00 | Senin 16.00–23.00 | Selasa 16.00–23.00,NaN,-7.057205,110.463189,0813-2515-7257,23,Tembalang,Meteseh
15,"Bakmi Surabaya ""cak Pri""","Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.1,5,82.0,Rabu 16.00–23.30 | Kamis 16.00–23.30 | Jumat 16.00–23.30 | Sabtu 16.00–23.30 | Minggu 16.00–23.30 | Senin 16.00–23.30 | Selasa 16.00–23.30,Rp 1–25.000,-7.041143,110.479252,0813-2559-2036,26,Tembalang,Sendangmulyo
16,Bakmi Kongsian,"Ruko AD, Ruko, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Rumah Makan,4.8,5,20.0,Tidak ada info jam buka,Rp 1–25.000,-7.065352,110.461017,NaN,28,Tembalang,Meteseh
17,Bakmie Jowo Mas Jenggot,"Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.3,5,27.0,Tidak ada info jam buka,Rp 1–25.000,-7.037252,110.474049,NaN,30,Tembalang,Sendangmulyo
18,Bakmi Jowo Pak Brewok,"Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.8,5,77.0,Rabu 17.00–23.00 | Kamis 17.00–23.00 | Jumat 17.00–23.00 | Sabtu 17.00–23.00 | Minggu 17.00–23.00 | Senin 17.00–23.00 | Selasa 17.00–23.00,Rp 1–25.000,-7.042782,110.479129,0821-3485-7772,33,Tembalang,Sendangmulyo
19,Bakmi Surabaya,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,3.8,5,10.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.058050,110.471033,0813-2669-4979,35,Tembalang,Meteseh
20,"BAKMI SUROBOYO MAS NDUT (YUDI),METESEH","Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,4.3,5,8.0,Rabu 17.30–23.00 | Kamis 17.30–23.00 | Jumat 17.30–23.00 | Sabtu 17.30–23.00 | Minggu 17.30–23.00 | Senin 17.30–23.00 | Selasa 17.30–23.00,NaN,-7.052854,110.471467,0878-3106-0032,37,Tembalang,Meteseh
21,BAKMIE SURABAYA CAK BAGUS GROUP,"WFVC+7CQ, Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,4.4,5,13.0,Tidak ada info jam buka,Rp 1–25.000,-7.056775,110.471108,0821-3331-2021,38,Tembalang,Meteseh
22,Pondok Bakmi Bu Tarno,"XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Tembalang, Semarang City, Central Java 50273",Kafe,4.4,5,97.0,Rabu 18.00–00.00 | Kamis 18.00–00.00 | Jumat 18.00–00.00 | Sabtu 18.00–00.00 | Minggu 18.00–00.00 | Senin 18.00–00.00 | Selasa 18.00–00.00,Rp 1–25.000,-7.023199,110.458424,085287830644,44,Tembalang,Kedungmundu
23,Bakmi Jowo Mas Ndut,"Jl. Dinar Elok Raya No.K2 No.5, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,3.8,5,21.0,Rabu 16.30–00.00 | Kamis 16.30–00.00 | Jumat 16.30–00.00 | Sabtu 16.30–00.00 | Minggu 16.30–00.00 | Senin 16.30–00.00 | Selasa 16.30–00.00,Rp 1–25.000,-7.060398,110.469121,NaN,45,Tembalang,Meteseh
24,Bakmi Jowo Pak Gito,"XFF5+9Q6, Jl. Sambiroto Raya, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,4.3,5,22.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,Rp 1–25.000,-7.026584,110.459377,0812-2527-7968,46,Tembalang,Sambiroto
25,Bakmi jowo Petruk,"Jl. Fatmawati No.175, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.3,5,11.0,Rabu Buka 24 jam | Kamis Buka 24 jam | Jumat Buka 24 jam | Sabtu Buka 24 jam | Minggu Buka 24 jam | Senin Buka 24 jam | Selasa Buka 24 jam,Rp 1–25.000,-7.023638,110.468344,0889-3316-417,49,Tembalang,Kedungmundu
26,Bakmi jowo dan nasi goreng bintang lima,"Depas puskesmas Jl. Kompol R Soekanto, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Nasi Goreng,5.0,5,16.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,Rp 1–25.000,-7.044765,110.460857,0813-2900-2728,50,Tembalang,Mangunharjo
27,Bakmi Jowo Bu Hadi,"Jalan Prof. Suharso ,Meteseh, Tembalang, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,4.0,5,28.0,Rabu 16.30–00.00 | Kamis 16.30–00.00 | Jumat 16.30–00.00 | Sabtu 16.30–00.00 | Minggu 16.30–00.00 | Senin 16.30–00.00 | Selasa 16.30–00.00,Rp 1–25.000,-7.056714,110.464707,0812-4248-4643,51,Tembalang,Meteseh
28,Bakmi Jowo Nasi Goreng KADONG TRESNO,"Jl. Sambiroto Raya No.45A, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,3.1,5,64.0,Rabu 17.00–01.00 | Kamis 17.00–01.00 | Jumat 17.00–01.00 | Sabtu 17.00–01.00 | Minggu 17.00–01.00 | Senin 17.00–01.00 | Selasa 17.00–01.00,Rp 1–25.000,-7.029968,110.458956,0821-3525-5678,54,Tembalang,Sambiroto
29,Bakmi Jowo Risqi,"Jl. Bougenville Dalam No.Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.7,5,7.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.044840,110.474418,0898-3327-48701,55,Tembalang,Sendangmulyo
30,Bakmi Jowo Mas Nang,"perum klipang Blk. P XIV, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",Restoran Mie,4.7,5,6.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,Rp 1–25.000,-7.044950,110.479215,NaN,56,Tembalang,Sendangmulyo
31,Bakmi jowo pak wito,"Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Asia,3.9,5,16.0,Rabu 17.00–01.00 | Kamis 17.00–01.00 | Jumat 17.00–01.00 | Sabtu 17.00–01.00 | Minggu 17.00–01.00 | Senin 17.00–01.00 | Selasa 17.00–01.00,NaN,-7.037739,110.476659,0851-0010-6508,58,Tembalang,Sendangmulyo
32,Bakmi Jowo Mas Jon,"XF2H+RJR, Bundaran Simpang 4 Jl. Klipang, Sendangmulyo, Tembalang, Semarang City, Central Java 50272",Restoran Mie,4.4,5,5.0,Rabu 17.00–23.00 | Kamis 17.00–23.00 | Jumat 17.00–23.00 | Sabtu 17.00–23.00 | Minggu 17.00–23.00 | Senin 17.00–23.00 | Selasa 17.00–23.00,Rp 1–25.000,-7.047890,110.479006,NaN,59,Tembalang,Sendangmulyo
33,Bakmi Nyemek Keluarga,"Perum Jl. Wanamukti No.16 Blok E4, Sambiroto, Tembalang, Semarang City, Central Java 50276",Restoran Mie,4.1,5,9.0,Rabu 10.00–22.00 | Kamis 10.00–22.00 | Jumat 10.00–22.00 | Sabtu 10.00–22.00 | Minggu 10.00–22.00 | Senin 10.00–22.00 | Selasa 10.00–22.00,NaN,-7.030702,110.461416,0858-7066-7204,60,Tembalang,Sambiroto
34,Bakmi Jowo Pak Waris 2,"XFC9+W3W, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.3,5,14.0,Rabu 16.00–00.00 | Kamis 16.00–00.00 | Jumat 16.00–00.00 | Sabtu 16.00–00.00 | Minggu 16.00–00.00 | Senin 16.00–00.00 | Selasa 16.00–00.00,Rp 1–25.000,-7.027648,110.467695,0858-7550-5366,62,Tembalang,Sendangmulyo
35,Nasi Goreng & Bakmi Jawa (Graha Metro),"Graha Metro No.12B Blk B, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran,4.0,5,24.0,Rabu 15.00–00.00 | Kamis 15.00–00.00 | Jumat 15.00–00.00 | Sabtu 15.00–00.00 | Minggu 15.00–00.00 | Senin 15.00–00.00 | Selasa 15.00–00.00,Rp 1–25.000,-7.059470,110.476822,0856-4334-8465,63,Tembalang,Meteseh
36,Bakmi Jowo Solo,"Jl. Tulus Harapan No.4 Blk C, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,5.0,5,1.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.035407,110.469058,0856-2751-314,64,Tembalang,Sendangmulyo
37,Bakmi Jowo Sederhana,"Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Mie,4.3,5,4.0,Rabu 18.00–00.00 | Kamis 18.00–00.00 | Jumat 18.00–00.00 | Sabtu 18.00–00.00 | Minggu 18.00–00.00 | Senin 18.00–00.00 | Selasa 18.00–00.00,NaN,-7.023244,110.468932,NaN,66,Tembalang,Kedungmundu
38,Bakmi Jowo Pak Harno,"WFQ7+R2R, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,4.2,5,5.0,Rabu 17.00–02.00 | Kamis 17.00–02.00 | Jumat 17.00–02.00 | Sabtu 17.00–02.00 | Minggu 17.00–02.00 | Senin 17.00–02.00 | Selasa 17.00–02.00,Rp 1–25.000,-7.060381,110.462520,NaN,67,Tembalang,Meteseh
39,Bakmi surabaya mas gondrong,"Klipang blok R 7 No.7, RT.05/RW.06, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Warung nasi,4.5,5,8.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.045793,110.480462,0813-2622-3276,68,Tembalang,Sendangmulyo
40,"Bakmi Suroboyo,cak Kumis_Gg.Nirwanasari 1/24,Tembalang,kota Semarang,Jawa Tengah 50275","WCQQ+M8C, Gg. Nirwana Sari I, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",Restoran,3.4,5,NaN,Rabu 03.20–12.15 | Kamis 03.20–12.15 | Jumat 03.20–12.15 | Sabtu 03.20–12.15 | Minggu 03.20–12.15 | Senin 03.20–12.15 | Selasa 03.20–12.15,NaN,-7.060814,110.438265,0857-2717-0046,69,Tembalang,Tembalang
41,Bakmi Jowo mas Karyo,"XF99+X3F, Jl. Wanamukti, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran Mie,4.6,5,5.0,Rabu 11.00–21.00 | Kamis 11.00–21.00 | Jumat 11.00–21.00 | Sabtu 11.00–21.00 | Minggu 11.00–21.00 | Senin 11.00–21.00 | Selasa 11.00–21.00,Rp 1–25.000,-7.030051,110.467665,NaN,70,Tembalang,Sendangmulyo
42,Bakmi Jowo Pak No,"XFG6+25P, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Mie,3.8,5,4.0,Rabu 04.00–01.00 | Kamis 04.00–01.00 | Jumat 04.00–01.00 | Sabtu 04.00–01.00 | Minggu 04.00–01.00 | Senin 04.00–01.00 | Selasa 04.00–01.00,NaN,-7.024920,110.460452,0857-9916-0449,72,Tembalang,Sambiroto
43,Bakmi Jowo Pak triss,"XFQ3+RXP, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran Keluarga,5.0,5,2.0,Rabu 17.30–00.00 | Kamis 17.30–00.00 | Jumat 17.30–00.00 | Sabtu 17.30–00.00 | Minggu 17.30–00.00 | Senin 17.30–00.00 | Selasa 17.30–00.00,NaN,-7.010373,110.454931,0812-2518-0163,74,Tembalang,Sendangguwo
44,Warung TUMAN - Nasi Goreng & Bakmi Tuman,"Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Nasi Goreng,5.0,5,12.0,Rabu 17.00–22.00 | Kamis 17.00–22.00 | Jumat 17.00–22.00 | Sabtu 17.00–22.00 | Minggu 17.00–22.00 | Senin 17.00–22.00 | Selasa 17.00–22.00,NaN,-7.053261,110.477665,NaN,76,Tembalang,Meteseh
45,Bakmi Jowo Pak Sis - Meteseh,"Jl. Bukit Klp. Gading I No.32, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271",Restoran Mie,5.0,5,1.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.065751,110.459820,0822-2096-6500,77,Tembalang,Meteseh
46,Pondok Bakmi Jowo Siper,"Jl. kd.mundu No.12, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran,4.7,5,3.0,Rabu 17.00–00.00 | Kamis 17.00–00.00 | Jumat 17.00–00.00 | Sabtu 17.00–00.00 | Minggu 17.00–00.00 | Senin 17.00–00.00 | Selasa 17.00–00.00,NaN,-7.022240,110.457589,0896-3533-3539,78,Tembalang,Kedungmundu
47,"Bakmi Jowo ""RiLEX"" Nasi Goreng","Jalan Kedung Mundu Raya No.23B, Sambiroto, Tembalang, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274",Restoran Nasi Goreng,4.4,5,21.0,Rabu 19.00–21.00 | Kamis 19.00–21.00 | Jumat 19.00–21.00 | Sabtu 19.00–21.00 | Minggu 19.00–21.00 | Senin 19.00–21.00 | Selasa 19.00–21.00,NaN,-7.018516,110.455762,NaN,79,Tembalang,Kedungmundu
48,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Restoran Indonesia,5.0,5,2.0,Tidak ada info jam buka,NaN,-7.060934,110.462336,NaN,81,Tembalang,JayaMeteseh
49,Bakmi dan Nasi Goreng Pak Har,"WCMP+5WR, Jl. Mulawarman Raya, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran,5.0,5,2.0,Rabu 18.00–23.00 | Kamis 18.00–23.00 | Jumat 18.00–23.00 | Sabtu 18.00–23.00 | Minggu 18.00–23.00 | Senin 18.00–23.00 | Selasa 18.00–23.00,NaN,-7.067003,110.437254,NaN,82,Tembalang,Kramas
50,Warung Bakmi Dan Nasi Goreng Mas MR,"WCPV+66W, Jl. Gondang Timur IV, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Restoran cepat saji,4.8,5,5.0,Tidak ada info jam buka,Rp 1–25.000,-7.064380,110.443083,0857-2870-8081,87,Tembalang,Bulusan
51,BAKMI DD,"Jl. Gondang Raya No.16, RT.3/RW.1, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",Rumah Makan,5.0,5,8.0,Rabu 10.00–23.00 | Kamis 10.00–23.00 | Jumat 10.00–23.00 | Sabtu 10.00–23.00 | Minggu 10.00–23.00 | Senin 10.00–23.00 | Selasa 10.00–23.00,NaN,-7.061740,110.441422,0857-1260-0393,88,Tembalang,Bulusan
52,Bakmi jowo seger,"XFP2+M5R, Jl. Kedungmundu, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Disimpan,5.0,5,1.0,Rabu 17.00–01.00 | Kamis 17.00–01.00 | Jumat 17.00–01.00 | Sabtu 17.00–01.00 | Minggu 17.00–01.00 | Senin 17.00–01.00 | Selasa 17.00–01.00,NaN,-7.013265,110.450394,NaN,90,Tembalang,Kedungmundu
53,Nasi Goreng dan Bakmi Jowo Doa Ibu,"Jl. Sambiroto Raya No.82-80, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276",Restoran Nasi Goreng,4.7,5,6.0,Rabu 17.00–02.00 | Kamis 17.00–02.00 | Jumat 17.00–02.00 | Sabtu 17.00–02.00 | Minggu 17.00–02.00 | Senin 17.00–02.00 | Selasa 17.00–02.00,NaN,-7.027292,110.459281,0823-3783-7795,93,Tembalang,Sambiroto
54,Warung Bakmi Jowo Mas Tri,"Jl. Gondang Raya No.5, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275",Restoran Indonesia,5.0,5,2.0,Tutup permanen,NaN,-7.061108,110.441839,NaN,96,Tembalang,Bulusan
55,"Bakmi Jowo & Nasi Goreng ""Kang Gepeng""","Jl. Banjarsari Selatan No.51-55, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268",Tutup permanen,4.6,5,7.0,Tutup permanen,NaN,-7.062704,110.435862,Tutup permanen,101,Tembalang,Bulusan
56,Bakmi & Nasgor Mas Hendrik,"Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277",Tutup permanen,5.0,5,1.0,Tutup permanen,NaN,-7.060861,110.445378,0823-2418-2407,102,Tembalang,Bulusan
57,Nasi Goreng & Bakmi Jawa Manggala,"Jl. Bukit Bougenvil Raya No.8, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272",Restoran,5.0,5,1.0,Rabu 07.00–00.48 | Kamis 07.00–00.48 | Jumat 07.00–00.48 | Sabtu 07.00–00.48 | Minggu 07.00–00.48 | Senin 07.00–00.48 | Selasa 07.00–00.48,NaN,-7.044305,110.474609,0852-2018-0662,104,Tembalang,Sendangmulyo
58,Bakmi Djowo 14,"Jl. Sendang Dahlia No.10, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273",Restoran,4.9,5,NaN,Rabu 11.00–21.00 | Kamis 11.00–21.00 | Jumat 11.00–21.00 | Sabtu 11.00–21.00 | Minggu 10.00–21.00 | Senin 11.00–21.00 | Selasa 11.00–21.00,NaN,-7.015754,110.463260,0895-3279-86605,105,Tembalang,Sendangguwo
59,"Bakmi Jawa ""Mbah No""","Jl. Mulawarman Sel. II No.15, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278",Restoran Mie,5.0,5,NaN,Tidak ada info jam buka,NaN,-7.069933,110.439127,NaN,106,Tembalang,Kramas